"""Remove local cache/build clutter from the repo root.

    uv run python scripts/dev/cleanup.py

Deletes, if present: .mypy_cache, .pytest_cache, .ruff_cache, build, dist.
All are gitignored and safely regenerated by the next lint/test/build run.
"""

from __future__ import annotations

import shutil
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

TARGETS = [".mypy_cache", ".pytest_cache", ".ruff_cache", "build", "dist"]


def cleanup() -> None:
    for name in TARGETS:
        path = REPO_ROOT / name
        if path.exists():
            shutil.rmtree(path)
            print(f"removed {path}")
        else:
            print(f"skipped {path} (not present)")


if __name__ == "__main__":
    cleanup()
