"""Remove local cache/build clutter from the repo root.

    uv run python scripts/dev/cleanup.py

Deletes, if present: .mypy_cache, .pytest_cache, .ruff_cache, build, dist.
All are gitignored and safely regenerated by the next lint/test/build run.
"""

from __future__ import annotations

import shutil
from pathlib import Path


class Cleanup:
    """Removes local cache/build directories from a repository root."""

    REPO_ROOT = Path(__file__).resolve().parents[2]
    TARGETS = (".mypy_cache", ".pytest_cache", ".ruff_cache", "build", "dist")

    def __init__(
        self,
        root: Path = REPO_ROOT,
        targets: tuple[str, ...] = TARGETS,
    ) -> None:
        self.root = root
        self.targets = targets

    def run(self) -> None:
        for name in self.targets:
            self._remove(self.root / name)

    @staticmethod
    def _remove(path: Path) -> None:
        if path.exists():
            shutil.rmtree(path)
            print(f"removed {path}")
        else:
            print(f"skipped {path} (not present)")


if __name__ == "__main__":
    Cleanup().run()
