"""Keep everything derived from `type.json` in step: the `type-<id>` extras in the published
pyprojects and the `filetypes.json` catalog the Windows installer reads.

    python scripts/dev/filetypes.py          # regenerate
    python scripts/dev/filetypes.py --check  # exit 1 on drift (CI)
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
TYPES_DIR = REPO_ROOT / "packages" / "vethuq-core" / "src" / "vethuq_core" / "filetypes"
PYPROJECTS = [
    REPO_ROOT / "packages" / "vethuq-core" / "pyproject.toml",
    REPO_ROOT / "packages" / "vethuq" / "pyproject.toml",
]
CATALOG = REPO_ROOT / "packages" / "vethuq-ui" / "installer" / "filetypes.json"
# The same catalog as Pascal, since Inno Setup cannot parse JSON; included by vethuq.iss.
INNO_INCLUDE = REPO_ROOT / "packages" / "vethuq-ui" / "installer" / "filetypes.iss"

BEGIN = "# BEGIN generated from filetypes/*/type.json - run scripts/dev/filetypes.py"
END = "# END generated"
_BLOCK = re.compile(rf"\n?{re.escape(BEGIN)}.*?{re.escape(END)}\n", re.DOTALL)


def load_manifests() -> list[dict]:
    return sorted(
        (json.loads(p.read_text("utf-8")) for p in TYPES_DIR.glob("*/type.json")),
        key=lambda m: m["id"],
    )


def extras_block(manifests: list[dict]) -> str:
    lines = ["", BEGIN, "[project.optional-dependencies]"]
    for m in manifests:
        requires = ", ".join(json.dumps(r) for r in m["requires"])
        lines.append(f"{m['extra']} = [{requires}]")
    lines.append(END)
    return "\n".join(lines) + "\n"


def with_extras(text: str, manifests: list[dict]) -> str:
    block = extras_block(manifests)
    if _BLOCK.search(text):
        return _BLOCK.sub(lambda _: block, text)
    # First run: put the block right after the [project] table's dependencies.
    marker = "\n[project.scripts]" if "\n[project.scripts]" in text else "\n[build-system]"
    return text.replace(marker, block + marker, 1)


def catalog(manifests: list[dict]) -> str:
    entries = [
        {
            "id": m["id"],
            "label": m["label"],
            "extensions": m["extensions"],
            "extra": m["extra"],
            "approx_size_mb": m["approx_size_mb"],
            "default": m["default"],
        }
        for m in manifests
    ]
    return json.dumps({"file_types": entries}, indent=2) + "\n"


def inno_include(manifests: list[dict]) -> str:
    def case(name: str, values: list[str], kind: str) -> list[str]:
        out = [f"function FileType{name}(Index: Integer): {kind};", "begin", "  case Index of"]
        out += [f"    {i}: Result := {v};" for i, v in enumerate(values)]
        return out + ["  end;", "end;", ""]

    quote = lambda text: "'" + text.replace("'", "''") + "'"  # noqa: E731
    lines = ["{ Generated by scripts/dev/filetypes.py from filetypes.json - do not edit. }", ""]
    lines += [f"const FileTypeCount = {len(manifests)};", ""]
    ids = [quote(m["id"]) for m in manifests]
    labels = [
        quote(
            f"{m['label']} (about {m['approx_size_mb']} MB)" if m["approx_size_mb"] else m["label"]
        )
        for m in manifests
    ]
    defaults = [str(m["default"]).lower() for m in manifests]
    lines += case("Id", ids, "string") + case("Label", labels, "string")
    lines += case("Default", defaults, "Boolean")
    return "\n".join(lines)


def problems(manifests: list[dict]) -> list[str]:
    found = []
    for pyproject in PYPROJECTS:
        text = pyproject.read_text("utf-8")
        for m in manifests:
            if m["default"]:
                # pip has no default extras, so the default type's requirements must be base ones.
                for requirement in m["requires"]:
                    if json.dumps(requirement) not in text.split(BEGIN)[0]:
                        found.append(f"{pyproject}: default type {m['id']} needs {requirement}")
    return found


def main(check: bool) -> int:
    manifests = load_manifests()
    wanted = {p: with_extras(p.read_text("utf-8"), manifests) for p in PYPROJECTS}
    wanted[CATALOG] = catalog(manifests)
    wanted[INNO_INCLUDE] = inno_include(manifests)
    drift = [p for p, text in wanted.items() if not p.exists() or p.read_text("utf-8") != text]
    errors = problems(manifests)
    if check:
        for path in drift:
            print(f"out of date: {path.relative_to(REPO_ROOT)} (run scripts/dev/filetypes.py)")
        for error in errors:
            print(error)
        return 1 if drift or errors else 0
    for path in drift:
        path.write_text(wanted[path], encoding="utf-8")
        print(f"wrote {path.relative_to(REPO_ROOT)}")
    for error in errors:
        print(error)
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main("--check" in sys.argv[1:]))
