"""Derive every branded asset from the one master icon, `vethuq_ui/assets/brand/vethuq.png`.

Writes the Windows `.ico`, the Inno Setup wizard images, the console logo
(`vethuq_cli/logo.py`) and the installer's `LICENSE.rtf` (with the logo on top) from
`installer/LICENSE.md`. Needs only pillow:

    uv run python scripts/dev/generate_brand.py
"""

from __future__ import annotations

import binascii
import io
import re
from pathlib import Path

from PIL import Image

REPO_ROOT = Path(__file__).resolve().parents[2]
UI = REPO_ROOT / "packages" / "vethuq-ui"
BRAND = UI / "src" / "vethuq_ui" / "assets" / "brand"
INSTALLER = UI / "installer"
CLI_LOGO = REPO_ROOT / "packages" / "vethuq-cli" / "src" / "vethuq_cli" / "logo.py"

_ICO_SIZES = [(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)]
_WIZARD_BACKGROUND = (255, 255, 255)
_CONSOLE_COLUMNS = 28


class Brand:
    @staticmethod
    def master() -> Image.Image:
        return Image.open(BRAND / "vethuq.png").convert("RGBA")

    @staticmethod
    def write_icon(master: Image.Image) -> None:
        for target in (BRAND / "vethuq.ico", INSTALLER / "vethuq.ico"):
            master.save(target, format="ICO", sizes=_ICO_SIZES)

    @staticmethod
    def _on_background(image: Image.Image, size: tuple[int, int]) -> Image.Image:
        """The icon centred (fit) on the wizard's white page, as a flat RGB bitmap."""
        canvas = Image.new("RGB", size, _WIZARD_BACKGROUND)
        edge = min(size)
        icon = image.resize((edge, edge), Image.Resampling.LANCZOS)
        canvas.paste(icon, ((size[0] - edge) // 2, (size[1] - edge) // 2), icon)
        return canvas

    @staticmethod
    def write_wizard_images(master: Image.Image) -> None:
        # Inno scales these at higher DPI; the sidebar is 164x314, the header 55x55.
        Brand._on_background(master, (55, 55)).save(INSTALLER / "wizard_small.bmp")
        Brand._on_background(master, (164, 314)).save(INSTALLER / "wizard_large.bmp")

    @staticmethod
    def write_console_logo(master: Image.Image) -> None:
        """Half-block truecolor art: every character cell stacks two pixels (▀ / ▄)."""
        px = master.resize((_CONSOLE_COLUMNS, _CONSOLE_COLUMNS), Image.Resampling.LANCZOS)

        def color(x: int, y: int) -> str | None:
            r, g, b, a = px.getpixel((x, y))
            return f"#{r:02x}{g:02x}{b:02x}" if a >= 96 else None

        rows = []
        for y in range(0, _CONSOLE_COLUMNS, 2):
            cells = []
            for x in range(_CONSOLE_COLUMNS):
                top, bottom = color(x, y), color(x, y + 1)
                if top and bottom:
                    cells.append(f"[{top} on {bottom}]\u2580[/]")
                elif top:
                    cells.append(f"[{top}]\u2580[/]")
                elif bottom:
                    cells.append(f"[{bottom}]\u2584[/]")
                else:
                    cells.append(" ")
            rows.append("".join(cells))
        lines = ",\n".join(f"        {row!r}" for row in rows)
        CLI_LOGO.write_text(
            '"""The VethuQ icon as truecolor half-block art. Generated by '
            'scripts/dev/generate_brand.py - do not edit."""\n\n'
            "# ruff: noqa: E501\n\n"
            "from __future__ import annotations\n\n\n"
            "class Logo:\n"
            "    ROWS = (\n"
            f"{lines},\n"
            "    )\n\n"
            "    @staticmethod\n"
            "    def markup() -> str:\n"
            '        return "\\n".join(Logo.ROWS)\n',
            encoding="utf-8",
        )

    @staticmethod
    def _cw(*words: str) -> str:
        """RTF control words, e.g. `_cw("b", "fs34")` -> a backslash-prefixed run."""
        return "".join(chr(92) + w for w in words)

    @staticmethod
    def _rtf_escape(text: str) -> str:
        out = []
        for ch in text:
            if ch in (chr(92), "{", "}"):
                out.append(chr(92) + ch)
            elif ord(ch) > 127:
                code = ord(ch)
                out.append(chr(92) + "u" + str(code if code < 32768 else code - 65536) + "?")
            else:
                out.append(ch)
        return "".join(out)

    @staticmethod
    def _inline(text: str) -> str:
        """`**bold**` -> RTF bold, the rest escaped."""
        cw = Brand._cw
        parts = re.split(r"(\*\*.+?\*\*)", text)
        return "".join(
            "{" + cw("b") + " " + Brand._rtf_escape(p[2:-2]) + "}"
            if p.startswith("**")
            else Brand._rtf_escape(p)
            for p in parts
        )

    @staticmethod
    def write_license(master: Image.Image) -> None:
        cw = Brand._cw
        logo = io.BytesIO()
        master.resize((96, 96), Image.Resampling.LANCZOS).save(logo, format="PNG")
        hex_png = binascii.hexlify(logo.getvalue()).decode()
        par = cw("par")
        # picw/pich are the source size, picwgoal/pichgoal the display size in twips (96px = 1440).
        body = [
            "{"
            + cw("pict", "pngblip", "picw96", "pich96", "picwgoal1440", "pichgoal1440")
            + " "
            + hex_png
            + "}"
            + par * 2
        ]
        for line in (INSTALLER / "LICENSE.md").read_text("utf-8").splitlines():
            if line.startswith("# "):
                title = cw("fs34", "b") + " " + Brand._inline(line[2:]) + cw("b0", "fs20")
                body.append(title + par * 2)
            elif line.startswith("## "):
                head = cw("par", "fs26", "b") + " " + Brand._inline(line[3:]) + cw("b0", "fs20")
                body.append(head + par)
            elif line.startswith("- "):
                item = cw("li360", "fi-200", "bullet") + "  " + Brand._inline(line[2:])
                body.append(item + par + cw("li0", "fi0"))
            elif line.startswith("  ") and line.strip():
                body.append(cw("li560") + " " + Brand._inline(line.strip()) + par + cw("li0"))
            elif line.strip():
                body.append(Brand._inline(line) + par)
            else:
                body.append(par)
        header = "{" + cw("rtf1", "ansi", "deff0") + "{" + cw("fonttbl") + "{" + cw("f0", "fswiss")
        header += " Segoe UI;}}" + cw("f0", "fs20")
        rtf = header + chr(10) + chr(10).join(body) + chr(10) + "}"
        (INSTALLER / "LICENSE.rtf").write_text(rtf, encoding="ascii")

    @staticmethod
    def run() -> None:
        master = Brand.master()
        Brand.write_icon(master)
        Brand.write_wizard_images(master)
        Brand.write_console_logo(master)
        Brand.write_license(master)


if __name__ == "__main__":
    Brand.run()
