"""Keep everything derived from the manifests in step: the `type-<id>` and `search-<id>` extras
(plus `ocr-<id>` and `lang-<id>`) in the published pyprojects, and the catalogs and Inno Setup
includes the Windows installer reads.

    python scripts/dev/sync_extras.py          # regenerate
    python scripts/dev/sync_extras.py --check  # exit 1 on drift (CI)

Manifests: `filetypes/<id>/type.json` and `search/engines/manifests/<id>.json`,
`ocr/engines/manifests/<id>.json` and `ocr/languages/manifests/<id>.json`.
"""

from __future__ import annotations

import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
CORE = REPO_ROOT / "packages" / "vethuq-core" / "src" / "vethuq_core"
INSTALLER = REPO_ROOT / "packages" / "vethuq-ui" / "installer"
PYPROJECTS = [
    REPO_ROOT / "packages" / "vethuq-core" / "pyproject.toml",
    REPO_ROOT / "packages" / "vethuq" / "pyproject.toml",
]

BEGIN = "# BEGIN generated from the manifests - run scripts/dev/sync_extras.py"
END = "# END generated"
_BLOCK = re.compile(rf"\n?{re.escape(BEGIN)}.*?{re.escape(END)}\n", re.DOTALL)


@dataclass(frozen=True)
class Kind:
    """One family of installable features."""

    name: str  # what the catalog and Pascal functions are called
    manifests: str  # glob under CORE
    catalog: Path
    inno: Path
    json_key: str
    catalog_fields: tuple[str, ...]


KINDS = [
    Kind(
        "OcrEngine",
        "ocr/engines/manifests/*.json",
        INSTALLER / "ocr_engines.json",
        INSTALLER / "ocr_engines.iss",
        "ocr_engines",
        ("id", "label", "extra", "default"),
    ),
    Kind(
        "Language",
        "ocr/languages/manifests/*.json",
        INSTALLER / "languages.json",
        INSTALLER / "languages.iss",
        "languages",
        ("id", "label", "extra", "default"),
    ),
    Kind(
        "FileType",
        "filetypes/*/type.json",
        INSTALLER / "filetypes.json",
        INSTALLER / "filetypes.iss",
        "file_types",
        ("id", "label", "extensions", "extra", "approx_size_mb", "default"),
    ),
    Kind(
        "SearchEngine",
        "search/engines/manifests/*.json",
        INSTALLER / "search_engines.json",
        INSTALLER / "search_engines.iss",
        "search_engines",
        ("id", "label", "extra", "default"),
    ),
]


def load(kind: Kind) -> list[dict]:
    manifests = [json.loads(p.read_text("utf-8")) for p in CORE.glob(kind.manifests)]
    return sorted(manifests, key=lambda m: (not m["default"], m["id"]))


def extras_block(all_manifests: list[dict]) -> str:
    lines = ["", BEGIN, "[project.optional-dependencies]"]
    for m in sorted(all_manifests, key=lambda m: m["extra"]):
        # Non-default entries also pull in a marker distribution so pip records the choice.
        markers = [] if m["default"] else [f"vethuq-{m['extra']}"]
        requires = ", ".join(json.dumps(r) for r in [*m["requires"], *markers])
        lines.append(f"{m['extra']} = [{requires}]")
    lines.append(END)
    return "\n".join(lines) + "\n"


def with_extras(text: str, all_manifests: list[dict]) -> str:
    block = extras_block(all_manifests)
    if _BLOCK.search(text):
        return _BLOCK.sub(lambda _: block, text)
    # First run: put the block right after the [project] table's dependencies.
    marker = "\n[project.scripts]" if "\n[project.scripts]" in text else "\n[build-system]"
    return text.replace(marker, block + marker, 1)


def catalog(kind: Kind, manifests: list[dict]) -> str:
    entries = [{k: m[k] for k in kind.catalog_fields} for m in manifests]
    return json.dumps({kind.json_key: entries}, indent=2) + "\n"


def inno_include(kind: Kind, manifests: list[dict]) -> str:
    def quote(text: str) -> str:
        return "'" + text.replace("'", "''") + "'"

    def case(suffix: str, values: list[str], result_type: str) -> list[str]:
        out = [f"function {kind.name}{suffix}(Index: Integer): {result_type};", "begin"]
        out.append("  case Index of")
        out += [f"    {i}: Result := {v};" for i, v in enumerate(values)]
        return out + ["  end;", "end;", ""]

    def label(m: dict) -> str:
        size = m.get("approx_size_mb")
        return quote(f"{m['label']} (about {size} MB)" if size else m["label"])

    lines = [
        f"{{ Generated by scripts/dev/sync_extras.py from {kind.catalog.name} - do not edit. }}"
    ]
    lines += ["", f"const {kind.name}Count = {len(manifests)};", ""]
    lines += case("Id", [quote(m["id"]) for m in manifests], "string")
    lines += case("Label", [label(m) for m in manifests], "string")
    lines += case("Default", [str(m["default"]).lower() for m in manifests], "Boolean")
    return "\n".join(lines)


def problems(all_manifests: list[dict]) -> list[str]:
    found = []
    for pyproject in PYPROJECTS:
        base = pyproject.read_text("utf-8").split(BEGIN)[0]
        for m in all_manifests:
            if m["default"]:
                # pip has no default extras, so the default's requirements must be base ones.
                for requirement in m["requires"]:
                    if json.dumps(requirement) not in base:
                        found.append(f"{pyproject}: default {m['id']} needs {requirement}")
    return found


def main(check: bool) -> int:
    loaded = {kind.name: load(kind) for kind in KINDS}
    all_manifests = [m for manifests in loaded.values() for m in manifests]
    wanted = {p: with_extras(p.read_text("utf-8"), all_manifests) for p in PYPROJECTS}
    for kind in KINDS:
        wanted[kind.catalog] = catalog(kind, loaded[kind.name])
        wanted[kind.inno] = inno_include(kind, loaded[kind.name])
    drift = [p for p, text in wanted.items() if not p.exists() or p.read_text("utf-8") != text]
    errors = problems(all_manifests)
    if check:
        for path in drift:
            print(f"out of date: {path.relative_to(REPO_ROOT)} (run scripts/dev/sync_extras.py)")
    else:
        for path in drift:
            path.write_text(wanted[path], encoding="utf-8")
            print(f"wrote {path.relative_to(REPO_ROOT)}")
    for error in errors:
        print(error)
    return 1 if errors or (check and drift) else 0


if __name__ == "__main__":
    sys.exit(main("--check" in sys.argv[1:]))
