"""Export `search` results to a JSON or HTML file."""

from __future__ import annotations

import html
import json
import locale
from datetime import datetime
from pathlib import Path

from vethuq_core.branding import APP_NAME, APP_TAGLINE
from vethuq_core.search.search import SearchMatch
from vethuq_core.settings import SearchSettings


class Export:
    _HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{{APP_NAME}} search export: {{QUERY}}</title>
<style>
  body {
    font-family: -apple-system, Segoe UI, Roboto, sans-serif;
    margin: 2rem;
    color: #1a1a1a;
    background: #fafafa;
  }
  h1 { font-size: 1.25rem; }
  .meta { color: #666; margin-bottom: 1.5rem; }
  .results {
    background: #fff;
    border: 1px solid #ddd;
    border-radius: 6px;
    overflow: hidden;
  }
  .row-cells {
    display: grid;
    grid-template-columns: 20px 1.4fr 2fr 70px 100px;
    align-items: center;
    gap: 0.75rem;
  }
  .row-cells.header {
    padding: 0.6rem 1rem;
    background: #f0f0f0;
    font-weight: 600;
    border-bottom: 1px solid #ddd;
  }
  details.row summary.row-cells {
    padding: 0.6rem 1rem;
    border-bottom: 1px solid #eee;
    cursor: pointer;
    list-style: none;
  }
  details.row summary::-webkit-details-marker { display: none; }
  details.row:last-of-type summary { border-bottom: none; }
  .chevron { display: inline-block; transition: transform 0.15s; }
  details.row[open] .chevron { transform: rotate(90deg); }
  .file-path a { color: #0645ad; text-decoration: none; }
  .file-path a:hover { text-decoration: underline; }
  .snippet {
    padding: 0.75rem 1rem 1rem 2.75rem;
    font-family: Consolas, Menlo, monospace;
    white-space: pre-wrap;
    line-height: 1.4;
    background: #fafafa;
    border-bottom: 1px solid #eee;
  }
  .snippet mark { background: #ffe08a; padding: 0 2px; }
  footer { margin-top: 1.5rem; color: #999; font-size: 0.85rem; }
  footer .footer-title { font-weight: 600; }
</style>
</head>
<body>
<h1>Search export: {{QUERY}}</h1>
<p class="meta">{{RESULT_COUNT}} match(es) &middot; generated {{GENERATED_AT}}</p>
<div class="results">
  <div class="row-cells header">
    <span></span>
    <span>File Name</span>
    <span>File Path</span>
    <span>Page</span>
    <span>Total Pages</span>
  </div>
  {{ROWS}}
</div>
<footer>
  <div class="footer-title">Generated by {{APP_NAME}}</div>
  <div class="footer-subtitle">{{APP_TAGLINE}}</div>
</footer>
</body>
</html>
"""

    _ROW_TEMPLATE = """<details class="row">
  <summary class="row-cells">
    <span class="chevron">&#9656;</span>
    <span class="file-name">{{FILE_NAME}}</span>
    <span class="file-path"><a href="{{FILE_URI}}">{{FILE_PATH}}</a></span>
    <span>{{PAGE}}</span>
    <span>{{TOTAL_PAGES}}</span>
  </summary>
  <div class="snippet">{{SNIPPET}}</div>
</details>
"""

    @staticmethod
    def _matched_text(match: SearchMatch) -> str:
        prefix = "..." if match.truncated_before else ""
        suffix = "..." if match.truncated_after else ""
        return f"{prefix}{match.before}{match.matched}{match.after}{suffix}"

    @staticmethod
    def _file_uri(file_path: str) -> str:
        return Path(file_path).resolve().as_uri()

    @staticmethod
    def _generated_at() -> str:
        """The current local time, formatted per the user's locale (no ISO 'T' separator)."""
        try:
            locale.setlocale(locale.LC_TIME, "")
        except locale.Error:
            pass
        return datetime.now().astimezone().strftime("%c %Z").strip()

    @staticmethod
    def search_results(matches: list[SearchMatch], query: str, output: Path, format_: str) -> None:
        """Write `matches` for `query` to `output` as `format_` ('json' or 'html')."""
        if format_ not in SearchSettings.EXPORT_FORMATS:
            raise ValueError(f"format_ must be one of {SearchSettings.EXPORT_FORMATS}")
        if format_ == "json":
            Export._write_json(matches, query, output)
        else:
            Export._write_html(matches, query, output)

    @staticmethod
    def _write_json(matches: list[SearchMatch], query: str, output: Path) -> None:
        payload = {
            "query": query,
            "generated_at": Export._generated_at(),
            "result_count": len(matches),
            "matches": [
                {
                    "file_name": match.file_name,
                    "file_path": match.file_path,
                    "page_number": match.page_number,
                    "total_pages": match.total_pages,
                    "matched_text": Export._matched_text(match),
                }
                for match in matches
            ],
        }
        output.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    @staticmethod
    def _write_html(matches: list[SearchMatch], query: str, output: Path) -> None:
        rows = []
        for match in matches:
            page = str(match.page_number) if match.page_number is not None else "-"
            total_pages = str(match.total_pages) if match.total_pages is not None else "-"
            snippet = html.escape(Export._matched_text(match)).replace(
                html.escape(match.matched), f"<mark>{html.escape(match.matched)}</mark>", 1
            )
            row = (
                Export._ROW_TEMPLATE.replace(
                    "{{FILE_URI}}", html.escape(Export._file_uri(match.file_path))
                )
                .replace("{{FILE_NAME}}", html.escape(match.file_name))
                .replace("{{FILE_PATH}}", html.escape(match.file_path))
                .replace("{{PAGE}}", page)
                .replace("{{TOTAL_PAGES}}", total_pages)
                .replace("{{SNIPPET}}", snippet)
            )
            rows.append(row)

        document = (
            Export._HTML_TEMPLATE.replace("{{APP_NAME}}", html.escape(APP_NAME))
            .replace("{{APP_TAGLINE}}", html.escape(APP_TAGLINE))
            .replace("{{QUERY}}", html.escape(query))
            .replace("{{RESULT_COUNT}}", str(len(matches)))
            .replace("{{GENERATED_AT}}", html.escape(Export._generated_at()))
            .replace("{{ROWS}}", "\n".join(rows))
        )
        output.write_text(document, encoding="utf-8")
