{ Generated by scripts/dev/filetypes.py from filetypes.json - do not edit. }

const FileTypeCount = 3;

function FileTypeId(Index: Integer): string;
begin
  case Index of
    0: Result := 'jpg';
    1: Result := 'pdf';
    2: Result := 'png';
  end;
end;

function FileTypeLabel(Index: Integer): string;
begin
  case Index of
    0: Result := 'JPEG image';
    1: Result := 'PDF (about 25 MB)';
    2: Result := 'PNG image';
  end;
end;

function FileTypeDefault(Index: Integer): Boolean;
begin
  case Index of
    0: Result := false;
    1: Result := true;
    2: Result := false;
  end;
end;
