{ Generated by scripts/dev/sync_extras.py from languages.json - do not edit. }

const LanguageCount = 2;

function LanguageId(Index: Integer): string;
begin
  case Index of
    0: Result := 'en';
    1: Result := 'te';
  end;
end;

function LanguageLabel(Index: Integer): string;
begin
  case Index of
    0: Result := 'English';
    1: Result := 'Telugu';
  end;
end;

function LanguageDefault(Index: Integer): Boolean;
begin
  case Index of
    0: Result := true;
    1: Result := false;
  end;
end;
