{ Generated by scripts/dev/sync_extras.py from languages.json - do not edit. }

const LanguageCount = 1;

function LanguageId(Index: Integer): string;
begin
  case Index of
    0: Result := 'en';
  end;
end;

function LanguageLabel(Index: Integer): string;
begin
  case Index of
    0: Result := 'English';
  end;
end;

function LanguageDefault(Index: Integer): Boolean;
begin
  case Index of
    0: Result := true;
  end;
end;
