{ Generated by scripts/dev/sync_extras.py from ocr_engines.json - do not edit. }

const OcrEngineCount = 1;

function OcrEngineId(Index: Integer): string;
begin
  case Index of
    0: Result := 'paddle';
  end;
end;

function OcrEngineLabel(Index: Integer): string;
begin
  case Index of
    0: Result := 'PaddleOCR';
  end;
end;

function OcrEngineDefault(Index: Integer): Boolean;
begin
  case Index of
    0: Result := true;
  end;
end;
