{ Generated by scripts/dev/sync_extras.py from search_engines.json - do not edit. }

const SearchEngineCount = 6;

function SearchEngineId(Index: Integer): string;
begin
  case Index of
    0: Result := 'like';
    1: Result := 'exact';
    2: Result := 'full-text';
    3: Result := 'fuzzy';
    4: Result := 'lexical';
    5: Result := 'proximity';
  end;
end;

function SearchEngineLabel(Index: Integer): string;
begin
  case Index of
    0: Result := 'Contains (like)';
    1: Result := 'Exact';
    2: Result := 'Full-text (BM25)';
    3: Result := 'Fuzzy';
    4: Result := 'Word match (lexical)';
    5: Result := 'Proximity';
  end;
end;

function SearchEngineDefault(Index: Integer): Boolean;
begin
  case Index of
    0: Result := true;
    1: Result := false;
    2: Result := false;
    3: Result := false;
    4: Result := false;
    5: Result := false;
  end;
end;
