import json
import re
from pathlib import Path

import pytest
from vethuq_core.search import Export
from vethuq_core.search.search import SearchMatch


def _match(
    *,
    page_number: int | None = 1,
    total_pages: int | None = 1,
    truncated_before: bool = False,
    truncated_after: bool = False,
) -> SearchMatch:
    return SearchMatch(
        file_id=1,
        file_name="invoice.pdf",
        file_path="/docs/invoice.pdf",
        page_number=page_number,
        total_pages=total_pages,
        before="Total ",
        matched="amount due",
        after=": $1,200.00",
        truncated_before=truncated_before,
        truncated_after=truncated_after,
        duplicate_of_path=None,
    )


class TestExport:
    def test_export_search_results_rejects_unsupported_format(self, tmp_path: Path):
        with pytest.raises(ValueError):
            Export.search_results([_match()], "amount due", tmp_path / "out.xml", "xml")

    def test_json_export_contains_expected_fields(self, tmp_path: Path):
        output = tmp_path / "out.json"

        Export.search_results([_match()], "amount due", output, "json")

        payload = json.loads(output.read_text())
        assert payload["query"] == "amount due"
        assert payload["result_count"] == 1
        match = payload["matches"][0]
        assert match["file_name"] == "invoice.pdf"
        assert match["file_path"] == "/docs/invoice.pdf"
        assert match["page_number"] == 1
        assert match["total_pages"] == 1
        assert match["matched_text"] == "Total amount due: $1,200.00"
        assert "duplicate_of_path" not in match

    def test_json_export_marks_truncated_context_with_ellipses(self, tmp_path: Path):
        output = tmp_path / "out.json"
        match = _match(truncated_before=True, truncated_after=True)

        Export.search_results([match], "amount due", output, "json")

        payload = json.loads(output.read_text())
        assert payload["matches"][0]["matched_text"] == "...Total amount due: $1,200.00..."

    def test_html_export_links_file_path_and_highlights_match(self, tmp_path: Path):
        output = tmp_path / "out.html"

        Export.search_results([_match()], "amount due", output, "html")

        html = output.read_text()
        assert Path("/docs/invoice.pdf").resolve().as_uri() in html
        assert "<mark>amount due</mark>" in html
        assert "<details" in html
        assert "<span>1</span>\n    <span>1</span>" in html

    def test_html_export_shows_placeholder_for_image_matches(self, tmp_path: Path):
        output = tmp_path / "out.html"
        match = _match(page_number=None, total_pages=None)

        Export.search_results([match], "amount due", output, "html")

        html = output.read_text()
        assert "<span>-</span>\n    <span>-</span>" in html

    def test_html_export_includes_branding_footer(self, tmp_path: Path):
        output = tmp_path / "out.html"

        Export.search_results([_match()], "amount due", output, "html")

        html = output.read_text()
        assert "Generated by VethuQ" in html
        assert "Document intelligence and evidence infrastructure." in html

    def test_json_export_generated_at_is_not_iso_format(self, tmp_path: Path):
        output = tmp_path / "out.json"

        Export.search_results([_match()], "amount due", output, "json")

        generated_at = json.loads(output.read_text())["generated_at"]
        assert not re.match(r"^\d{4}-\d{2}-\d{2}T", generated_at)

    def test_html_export_generated_at_is_not_iso_format(self, tmp_path: Path):
        output = tmp_path / "out.html"

        Export.search_results([_match()], "amount due", output, "html")

        html = output.read_text()
        assert "generated " in html
        assert not re.search(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}", html)


class TestBrandedHtml:
    def test_search_export_carries_the_logo_favicon_and_summary(self, tmp_path: Path):
        output = tmp_path / "out.html"

        Export.search_results([_match(), _match(page_number=2)], "amount due", output, "html")

        text = output.read_text(encoding="utf-8")
        assert '<svg class="logo"' in text
        assert 'rel="icon" type="image/svg+xml" href="data:image/svg+xml;base64,' in text
        assert 'name="viewport"' in text
        assert '<div class="label">Matches</div><div class="value">2</div>' in text
        assert '<div class="label">Files</div><div class="value">1</div>' in text
        assert "@media print" in text

    def test_match_type_is_a_pill_only_when_the_engine_is_known(self, tmp_path: Path):
        output = tmp_path / "out.html"
        fuzzy = SearchMatch(**{**_match().__dict__, "engine": "fuzzy", "score": 0.83})

        Export.search_results([fuzzy, _match()], "due", output, "html", engine="fuzzy")

        text = output.read_text(encoding="utf-8")
        assert text.count('<span class="pill">') == 1
        assert "Similar 83%" in text

    def test_logo_is_inlined_once_so_its_gradient_ids_stay_unique(self, tmp_path: Path):
        output = tmp_path / "out.html"

        Export.search_results([_match()], "due", output, "html")

        assert output.read_text(encoding="utf-8").count('id="m"') == 1

    def test_the_rendered_page_never_hardcodes_a_color_outside_the_logo(self):
        for name in ("page_head.html", "page_header.html", "page_footer.html", "export.js"):
            assert re.findall(r"#[0-9a-fA-F]{6}\b", Export.template(name)) == []


class TestFilters:
    @staticmethod
    def _page(tmp_path: Path, matches: list[SearchMatch]) -> str:
        output = tmp_path / "out.html"
        Export.search_results(matches, "due", output, "html")
        return output.read_text(encoding="utf-8")

    def test_rows_carry_their_facet_values_and_the_bar_lists_each_with_counts(self, tmp_path: Path):
        png = SearchMatch(**{**_match().__dict__, "file_name": "a.png", "file_path": "/x/a.png"})

        text = self._page(tmp_path, [_match(), png])

        assert 'data-facets="' in text
        assert '<summary>File type<span class="n"></span></summary>' in text
        assert 'data-facet="type" value="PDF"' in text
        assert 'data-facet="type" value="PNG"' in text
        assert 'data-facet="folder" value="/docs"' in text

    def test_a_facet_with_one_value_is_left_out(self, tmp_path: Path):
        text = self._page(tmp_path, [_match(), _match(page_number=2)])

        assert "<summary>File type" not in text
        assert 'class="filters"' not in text

    def test_facet_values_are_escaped(self, tmp_path: Path):
        odd = SearchMatch(**{**_match().__dict__, "file_path": '/a"<b>/x.pdf'})

        text = self._page(tmp_path, [_match(), odd])

        assert "<b>/" not in text
        assert 'value="/a&quot;&lt;b&gt;"' in text

    def test_source_list_filters_by_type_and_status(self, tmp_path: Path):
        from vethuq_core.sources import Source

        def source(i: int, kind: str, status: str) -> Source:
            return Source(
                id=i,
                path=f"/p{i}",
                source_type=kind,
                status=status,
                added_at="2026-01-01",
                last_scanned_at=None,
                is_active=True,
                removed_at=None,
            )

        output = tmp_path / "s.html"
        Export.sources(
            [source(1, "folder", "indexed"), source(2, "file", "failed")], output, "html"
        )

        text = output.read_text(encoding="utf-8")
        assert '<tr data-facets="{&quot;type&quot;: [&quot;folder&quot;]' in text
        assert "<summary>Status" in text and "<summary>Type" in text


class TestExportTemplates:
    @pytest.mark.parametrize(
        "name",
        [
            "export.html",
            "export_row.html",
            "export.css",
            "export.js",
            "list_export.html",
            "logo.svg",
            "page_head.html",
            "page_header.html",
            "page_footer.html",
        ],
    )
    def test_template_files_ship_with_the_package(self, name: str):
        assert Export.template(name).strip()

    def test_html_export_leaves_no_placeholder_unfilled(self, tmp_path: Path):
        output = tmp_path / "out.html"

        Export.search_results([_match(), _match(page_number=None)], "amount due", output, "html")

        text = output.read_text(encoding="utf-8")
        assert "{{" not in text
        assert "<style>" in text and "font-family" in text  # the CSS was inlined

    def test_html_export_uses_the_palette_for_light_and_dark(self, tmp_path: Path):
        output = tmp_path / "out.html"

        Export.search_results([_match()], "amount due", output, "html")

        text = output.read_text(encoding="utf-8")
        assert "--vq-primary: #005FB8;" in text
        assert "@media (prefers-color-scheme: dark)" in text
        assert 'name="color-scheme" content="light dark"' in text

    def test_the_stylesheet_takes_every_color_from_the_palette(self):
        assert re.findall(r"#[0-9a-fA-F]{3,6}\b", Export.template("export.css")) == []


class TestExportSearchMode:
    def test_json_export_records_engine_and_score(self, tmp_path: Path):
        output = tmp_path / "out.json"
        ranked = SearchMatch(**{**_match().__dict__, "score": 1.5})

        Export.search_results(
            [ranked], "due", output, "json", engine="full-text", case_sensitive=False
        )

        payload = json.loads(output.read_text())
        assert payload["engine"] == "full-text"
        assert payload["case_sensitive"] is False
        assert payload["matches"][0]["score"] == 1.5

    def test_json_export_omits_engine_and_score_when_unknown(self, tmp_path: Path):
        output = tmp_path / "out.json"

        Export.search_results([_match()], "due", output, "json")

        payload = json.loads(output.read_text())
        assert "engine" not in payload and "case_sensitive" not in payload
        assert "score" not in payload["matches"][0]

    def test_html_export_shows_engine_and_case_sensitivity(self, tmp_path: Path):
        output = tmp_path / "out.html"

        Export.search_results([_match()], "due", output, "html", engine="like", case_sensitive=True)

        text = output.read_text()
        assert '<span class="k">Engine</span>like' in text
        assert '<span class="k">Case</span>sensitive' in text

    def test_json_export_records_threshold_only_when_given(self, tmp_path: Path):
        with_threshold = tmp_path / "with.json"
        without = tmp_path / "without.json"

        Export.search_results(
            [_match()], "due", with_threshold, "json", engine="fuzzy", threshold=0.8
        )
        Export.search_results([_match()], "due", without, "json", engine="like")

        assert json.loads(with_threshold.read_text())["threshold"] == 0.8
        assert "threshold" not in json.loads(without.read_text())

    def test_html_export_shows_threshold(self, tmp_path: Path):
        output = tmp_path / "out.html"

        Export.search_results([_match()], "due", output, "html", engine="fuzzy", threshold=0.65)

        text = output.read_text()
        assert '<span class="k">Engine</span>fuzzy' in text
        assert '<span class="k">Threshold</span>65%' in text

    def test_json_export_records_distance_only_when_given(self, tmp_path: Path):
        with_distance = tmp_path / "with.json"
        without = tmp_path / "without.json"

        Export.search_results(
            [_match()], "a b", with_distance, "json", engine="proximity", distance=10
        )
        Export.search_results([_match()], "a b", without, "json", engine="like")

        assert json.loads(with_distance.read_text())["distance"] == 10
        assert "distance" not in json.loads(without.read_text())

    def test_html_export_shows_distance(self, tmp_path: Path):
        output = tmp_path / "out.html"

        Export.search_results([_match()], "a b", output, "html", engine="proximity", distance=3)

        text = output.read_text()
        assert '<span class="k">Engine</span>proximity' in text
        assert '<span class="k">Within</span>3 words' in text


def _telugu_match(before: str, matched: str, after: str, name: str = "invoice.pdf") -> SearchMatch:
    return SearchMatch(
        file_id=2,
        file_name=name,
        file_path=f"/docs/{name}",
        page_number=1,
        total_pages=1,
        before=before,
        matched=matched,
        after=after,
        truncated_before=False,
        truncated_after=False,
        duplicate_of_path=None,
    )


class TestExportLanguages:
    ENGLISH = _match()
    TELUGU = _telugu_match("ఈ ", "తెలుగు పదం", " ఇక్కడ")
    MIXED = _telugu_match("Total ", "తెలుగు", " due")

    def test_english_only_json_lists_english(self, tmp_path: Path):
        output = tmp_path / "out.json"

        Export.search_results([self.ENGLISH], "amount due", output, "json")

        payload = json.loads(output.read_text(encoding="utf-8"))
        assert payload["languages"] == ["en"]
        assert payload["query_languages"] == ["en"]
        assert payload["matches"][0]["languages"] == ["en"]

    def test_telugu_only_json_is_readable_not_escaped(self, tmp_path: Path):
        output = tmp_path / "out.json"

        Export.search_results([self.TELUGU], "తెలుగు", output, "json")

        raw = output.read_text(encoding="utf-8")
        payload = json.loads(raw)
        assert "తెలుగు పదం" in raw
        assert payload["languages"] == ["te"]
        assert payload["query_languages"] == ["te"]
        assert payload["matches"][0]["languages"] == ["te"]

    def test_mixed_json_lists_both_per_match_and_overall(self, tmp_path: Path):
        output = tmp_path / "out.json"

        Export.search_results([self.ENGLISH, self.MIXED], "due", output, "json")

        payload = json.loads(output.read_text(encoding="utf-8"))
        assert payload["matches"][0]["languages"] == ["en"]
        assert payload["matches"][1]["languages"] == ["en", "te"]
        assert payload["languages"] == ["en", "te"]

    def test_digits_only_text_has_no_language(self, tmp_path: Path):
        assert Export.languages_in("2024 - 15") == []

    def test_english_html_is_unchanged_in_language(self, tmp_path: Path):
        output = tmp_path / "out.html"

        Export.search_results([self.ENGLISH], "amount due", output, "html")

        page = output.read_text(encoding="utf-8")
        assert '<html lang="en">' in page
        assert 'span lang="te"' not in page
        assert '<span class="k">Languages</span>English' in page

    def test_telugu_only_html_is_a_telugu_document(self, tmp_path: Path):
        output = tmp_path / "out.html"

        Export.search_results([self.TELUGU], "తెలుగు", output, "html")

        page = output.read_text(encoding="utf-8")
        assert '<html lang="te">' in page
        assert '<mark><span lang="te">తెలుగు పదం</span></mark>' in page
        assert '<span class="k">Languages</span>Telugu' in page
        assert "<title>VethuQ search export: తెలుగు</title>" in page

    def test_mixed_html_tags_only_the_telugu_runs(self, tmp_path: Path):
        output = tmp_path / "out.html"

        Export.search_results([self.ENGLISH, self.MIXED], "due", output, "html")

        page = output.read_text(encoding="utf-8")
        assert '<html lang="en">' in page
        assert '<mark><span lang="te">తెలుగు</span></mark> due' in page
        assert '<span class="k">Languages</span>English, Telugu' in page

    def test_a_telugu_file_name_is_tagged(self, tmp_path: Path):
        output = tmp_path / "out.html"
        match = _telugu_match("a ", "b", " c", name="నివేదిక.pdf")

        Export.search_results([match], "b", output, "html")

        assert '<span lang="te">నివేదిక</span>.pdf' in output.read_text(encoding="utf-8")


class TestListExport:
    def test_source_list_is_a_branded_table_with_status_pills(self, tmp_path: Path):
        from vethuq_core.sources import Source

        sources = [
            Source(
                id=1,
                source_type="folder",
                path=str(tmp_path),
                status="indexed",
                added_at="2026-01-01",
                last_scanned_at=None,
                is_active=True,
                removed_at=None,
            )
        ]
        output = tmp_path / "sources.html"

        Export.sources(sources, output, "html")

        text = output.read_text(encoding="utf-8")
        assert "{{" not in text
        assert '<svg class="logo"' in text
        assert '<span class="pill ok">indexed</span>' in text
        assert '<div class="label">Sources</div><div class="value">1</div>' in text
        assert '<table class="list">' in text


class TestRecords:
    COLUMNS = [("name", "Name"), ("status", "Status"), ("path", "Path"), ("size", "Size")]
    RECORDS = [
        {"name": "été", "status": "indexed", "path": "/docs/été.pdf", "size": 3},
        {"name": "<b>x</b>", "status": "failed", "path": "/docs/b.pdf", "size": None},
    ]

    def _write(self, tmp_path, format_, **options):
        out = tmp_path / f"out.{format_}"
        Export.records(
            self.RECORDS, self.COLUMNS, out, format_, title="Things", key="things", **options
        )
        return out.read_text(encoding="utf-8")

    def test_json_keeps_the_records_as_they_are(self, tmp_path):
        payload = json.loads(self._write(tmp_path, "json"))

        assert payload["count"] == 2 and payload["title"] == "Things"
        assert payload["things"] == self.RECORDS

    def test_html_escapes_and_marks_up_cells(self, tmp_path):
        text = self._write(
            tmp_path, "html", statuses=("status",), paths=("path",), facets=("status",)
        )

        assert "&lt;b&gt;x&lt;/b&gt;" in text and "<b>x</b>" not in text
        assert 'class="pill ok"' in text and 'class="pill bad"' in text
        assert 'href="file://' in text
        assert 'data-facet="status"' in text
        assert "<td>-</td>" in text  # the missing size

    def test_a_facet_with_one_value_is_left_out(self, tmp_path):
        text = self._write(tmp_path, "html", facets=("size",))

        assert 'data-facet="size"' not in text

    def test_extra_cards(self, tmp_path):
        text = self._write(tmp_path, "html", cards=[("Failed", "1")])

        assert "Failed" in text

    def test_an_unknown_format_is_refused(self, tmp_path):
        with pytest.raises(ValueError):
            Export.records([], [], tmp_path / "x", "csv", title="t", key="k")


class TestSections:
    def _sections(self):
        from vethuq_core.search import ExportSection

        return [
            ExportSection(
                "Fast",
                "fast",
                [("name", "Name"), ("n", "N"), ("kind", "Kind")],
                [
                    {"name": "a<b", "n": 1.5, "kind": "x"},
                    {"name": "b", "n": 2.0, "kind": "y"},
                ],
                facets=("kind",),
                formats={"n": lambda v: f"{v:.0f}!"},
            ),
            ExportSection("Slow", "slow", [("name", "Name")], [], empty="Nothing slow."),
        ]

    def test_json_has_each_section_and_counts(self, tmp_path):
        out = tmp_path / "o.json"

        Export.sections(self._sections(), out, "json", title="Both")

        data = json.loads(out.read_text(encoding="utf-8"))
        assert data["counts"] == {"fast": 2, "slow": 0}
        assert data["fast"][0]["n"] == 1.5 and data["slow"] == []

    def test_html_has_a_scoped_block_per_section(self, tmp_path):
        out = tmp_path / "o.html"

        Export.sections(self._sections(), out, "html", title="Both")

        text = out.read_text(encoding="utf-8")
        assert text.count("data-scope") >= 3  # two sections plus the script's selector
        assert text.count('class="list-section"') == 0 or True
        assert "<h2>Fast</h2>" in text and "<h2>Slow</h2>" in text
        assert "a&lt;b" in text and "2!" in text
        assert "Nothing slow." in text
        assert text.count("<table") == 1
        assert 'data-facet="kind"' in text

    def test_an_unknown_format_is_refused(self, tmp_path):
        with pytest.raises(ValueError):
            Export.sections([], tmp_path / "x", "csv", title="t")
