import json
import re
from pathlib import Path

import pytest
from vethuq_core.search import Export
from vethuq_core.search.search import SearchMatch


def _match(
    *,
    page_number: int | None = 1,
    total_pages: int | None = 1,
    truncated_before: bool = False,
    truncated_after: bool = False,
) -> SearchMatch:
    return SearchMatch(
        file_id=1,
        file_name="invoice.pdf",
        file_path="/docs/invoice.pdf",
        page_number=page_number,
        total_pages=total_pages,
        before="Total ",
        matched="amount due",
        after=": $1,200.00",
        truncated_before=truncated_before,
        truncated_after=truncated_after,
        duplicate_of_path=None,
    )


class TestExport:
    def test_export_search_results_rejects_unsupported_format(self, tmp_path: Path):
        with pytest.raises(ValueError):
            Export.search_results([_match()], "amount due", tmp_path / "out.xml", "xml")

    def test_json_export_contains_expected_fields(self, tmp_path: Path):
        output = tmp_path / "out.json"

        Export.search_results([_match()], "amount due", output, "json")

        payload = json.loads(output.read_text())
        assert payload["query"] == "amount due"
        assert payload["result_count"] == 1
        match = payload["matches"][0]
        assert match["file_name"] == "invoice.pdf"
        assert match["file_path"] == "/docs/invoice.pdf"
        assert match["page_number"] == 1
        assert match["total_pages"] == 1
        assert match["matched_text"] == "Total amount due: $1,200.00"
        assert "duplicate_of_path" not in match

    def test_json_export_marks_truncated_context_with_ellipses(self, tmp_path: Path):
        output = tmp_path / "out.json"
        match = _match(truncated_before=True, truncated_after=True)

        Export.search_results([match], "amount due", output, "json")

        payload = json.loads(output.read_text())
        assert payload["matches"][0]["matched_text"] == "...Total amount due: $1,200.00..."

    def test_html_export_links_file_path_and_highlights_match(self, tmp_path: Path):
        output = tmp_path / "out.html"

        Export.search_results([_match()], "amount due", output, "html")

        html = output.read_text()
        assert Path("/docs/invoice.pdf").resolve().as_uri() in html
        assert "<mark>amount due</mark>" in html
        assert "<details" in html
        assert "<span>1</span>\n    <span>1</span>" in html

    def test_html_export_shows_placeholder_for_image_matches(self, tmp_path: Path):
        output = tmp_path / "out.html"
        match = _match(page_number=None, total_pages=None)

        Export.search_results([match], "amount due", output, "html")

        html = output.read_text()
        assert "<span>-</span>\n    <span>-</span>" in html

    def test_html_export_includes_branding_footer(self, tmp_path: Path):
        output = tmp_path / "out.html"

        Export.search_results([_match()], "amount due", output, "html")

        html = output.read_text()
        assert "Generated by VethuQ" in html
        assert "Document intelligence and evidence infrastructure." in html

    def test_json_export_generated_at_is_not_iso_format(self, tmp_path: Path):
        output = tmp_path / "out.json"

        Export.search_results([_match()], "amount due", output, "json")

        generated_at = json.loads(output.read_text())["generated_at"]
        assert not re.match(r"^\d{4}-\d{2}-\d{2}T", generated_at)

    def test_html_export_generated_at_is_not_iso_format(self, tmp_path: Path):
        output = tmp_path / "out.html"

        Export.search_results([_match()], "amount due", output, "html")

        html = output.read_text()
        assert "generated " in html
        assert not re.search(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}", html)


class TestExportTemplates:
    @pytest.mark.parametrize("name", ["export.html", "export_row.html", "export.css"])
    def test_template_files_ship_with_the_package(self, name: str):
        assert Export.template(name).strip()

    def test_html_export_leaves_no_placeholder_unfilled(self, tmp_path: Path):
        output = tmp_path / "out.html"

        Export.search_results([_match(), _match(page_number=None)], "amount due", output, "html")

        text = output.read_text(encoding="utf-8")
        assert "{{" not in text
        assert "<style>" in text and "font-family" in text  # the CSS was inlined
