"""VethuQ — document intelligence and evidence infrastructure.

Library entry point. The `vethuq` CLI is installed separately as a console
script (see `pyproject.toml`); this module re-exports the public library
API. `vethuq._core` / `vethuq._cli` are vendored copies of the internal
`vethuq-core` / `vethuq-cli` workspace packages, generated by
`packages/vethuq/scripts/merge_sources.py` — not committed, not a public API.
"""

import time
from pathlib import Path

from vethuq._core.db import connect as _connect
from vethuq._core.db import default_db_path as _default_db_path
from vethuq._core.export import export_search_results as _export_search_results
from vethuq._core.index_runner import (
    AlreadyRunningError,
    IndexRun,
    IndexRunnerError,
    IndexState,
    StaleLockError,
)
from vethuq._core.index_runner import is_running as _is_running
from vethuq._core.index_runner import list_index_runs as _list_index_runs
from vethuq._core.index_runner import read_state as _read_state
from vethuq._core.index_runner import request_pause as _request_pause
from vethuq._core.index_runner import request_resume as _request_resume
from vethuq._core.index_runner import request_stop as _request_stop
from vethuq._core.index_runner import start_run as _start_run
from vethuq._core.ocr import DocumentResult
from vethuq._core.ocr import get_document_results as _get_document_results
from vethuq._core.search import SearchMatch
from vethuq._core.search import search_indexed_content as _search_indexed_content
from vethuq._core.settings import (
    OCR_ENGINE_MODES,
    SEARCH_EXPORT_FORMATS,
    STALE_LOCK_VALUES,
    InvalidSettingValueError,
    SettingsError,
)
from vethuq._core.settings import THREAD_WORKERS_AUTO as _THREAD_WORKERS_AUTO
from vethuq._core.settings import THREAD_WORKERS_MAX as _THREAD_WORKERS_MAX
from vethuq._core.settings import get_ocr_engine as _get_ocr_engine
from vethuq._core.settings import get_ocr_retry_attempts as _get_ocr_retry_attempts
from vethuq._core.settings import (
    get_removed_source_retention_minutes as _get_removed_source_retention_minutes,
)
from vethuq._core.settings import get_search_export_format as _get_search_export_format
from vethuq._core.settings import (
    get_search_snippet_context_chars as _get_search_snippet_context_chars,
)
from vethuq._core.settings import get_stale_lock as _get_stale_lock
from vethuq._core.settings import get_thread_workers as _get_thread_workers
from vethuq._core.settings import is_gpu_enabled as _is_gpu_enabled
from vethuq._core.settings import set_gpu_enabled as _set_gpu_enabled
from vethuq._core.settings import set_ocr_engine as _set_ocr_engine
from vethuq._core.settings import set_ocr_retry_attempts as _set_ocr_retry_attempts
from vethuq._core.settings import (
    set_removed_source_retention_minutes as _set_removed_source_retention_minutes,
)
from vethuq._core.settings import set_search_export_format as _set_search_export_format
from vethuq._core.settings import (
    set_search_snippet_context_chars as _set_search_snippet_context_chars,
)
from vethuq._core.settings import set_stale_lock as _set_stale_lock
from vethuq._core.settings import set_thread_workers as _set_thread_workers
from vethuq._core.sources import (
    Source,
    SourceAlreadyExistsError,
    SourceError,
    SourceNotFoundError,
    SourcePathError,
)
from vethuq._core.sources import add_source as _add_source
from vethuq._core.sources import get_source as _get_source
from vethuq._core.sources import list_sources as _list_sources
from vethuq._core.sources import remove_source as _remove_source
from vethuq._core.stats import ConfidenceMetric, ProcessingMetric
from vethuq._core.stats import get_confidence_metrics as _get_confidence_metrics
from vethuq._core.stats import get_processing_metrics as _get_processing_metrics
from vethuq._core.stats import reset_metrics as _reset_metrics

_STATE_POLL_SECONDS = 1.0

DB_PATH = _default_db_path()
"""Path to VethuQ's local SQLite database (the same one the CLI and desktop app use)."""

__all__ = [
    "OCR_ENGINE_MODES",
    "SEARCH_EXPORT_FORMATS",
    "STALE_LOCK_VALUES",
    "AlreadyRunningError",
    "ConfidenceMetric",
    "DB_PATH",
    "DocumentResult",
    "ExportFormatSettings",
    "GPUSettings",
    "Index",
    "IndexRun",
    "IndexRunnerError",
    "IndexSettings",
    "IndexState",
    "InvalidSettingValueError",
    "OcrEngineSettings",
    "OcrRetrySettings",
    "ProcessingMetric",
    "RemovedRetentionSettings",
    "Search",
    "SearchMatch",
    "SearchSettings",
    "Settings",
    "SettingsError",
    "SnippetSettings",
    "Source",
    "SourceAlreadyExistsError",
    "SourceError",
    "SourceNotFoundError",
    "SourcePathError",
    "Sources",
    "StaleLockError",
    "StaleLockSettings",
    "Stats",
    "ThreadWorkersSettings",
    "Vethuq",
]


def _coerce_target(target: str | int) -> str | int:
    """Digit strings mean a source id, same as the CLI accepts on the command line."""
    return int(target) if isinstance(target, str) and target.isdigit() else target


class Sources:
    """Register and manage files/folders as OCR/indexing sources.

    Not instantiated directly — use `Vethuq().sources`.
    """

    def add(self, path: str | Path) -> Source:
        """Register a file or folder as a source. Folders are indexed recursively.

        Re-adding a path that was previously removed reactivates it instead
        of failing. Raises `SourcePathError` if `path` doesn't exist, and
        `SourceAlreadyExistsError` if it's already an active source.
        """
        conn = _connect()
        try:
            return _add_source(conn, path)
        finally:
            conn.close()

    def list(self, include_inactive: bool = False) -> list[Source]:
        """Return registered sources, most recently added first."""
        conn = _connect()
        try:
            return _list_sources(conn, include_inactive)
        finally:
            conn.close()

    def remove(self, path_or_id: str | Path | int) -> Source:
        """Unregister a source by id or path. Raises `SourceNotFoundError` if it doesn't exist."""
        conn = _connect()
        try:
            return _remove_source(conn, path_or_id)
        finally:
            conn.close()


class Index:
    """Run and control background OCR indexing over registered sources.

    Not instantiated directly — use `Vethuq().index`.
    """

    def _wait_for_run(self, pid: int) -> IndexState | None:
        while True:
            time.sleep(_STATE_POLL_SECONDS)
            state = _read_state()
            if state is not None and state.pid == pid:
                if state.status in ("completed", "stopped", "failed"):
                    return state
                continue
            running, current_pid = _is_running()
            if not running or current_pid != pid:
                return _read_state()

    def run(
        self, target: str | int | None = None, *, force: bool = False, wait: bool = False
    ) -> int | IndexState | None:
        """Start OCR indexing on registered sources in the background.

        A source that's already fully indexed is still checked for files
        added or modified since the last run; unchanged files are left
        untouched. Returns the background process id, or, if `wait` is
        True, blocks until the run finishes and returns its final
        `IndexState` instead.

        Raises `AlreadyRunningError` if a run is already in progress, and
        `StaleLockError` if a previous run left a stale lock (`force=True`
        clears it). Raises `SourceNotFoundError` if `target` doesn't match a
        registered source.
        """
        pid = _start_run(str(target) if target is not None else None, force=force, restart=False)
        return self._wait_for_run(pid) if wait else pid

    def restart(
        self, target: str | int | None = None, *, force: bool = False, wait: bool = False
    ) -> int | IndexState | None:
        """Retry only previously-failed files, in the background. See `run`."""
        pid = _start_run(str(target) if target is not None else None, force=force, restart=True)
        return self._wait_for_run(pid) if wait else pid

    def status(self, target: str | int | None = None) -> IndexState | list[DocumentResult] | None:
        """Show background index run progress, or per-file detail for one source.

        With no `target`, returns the live/last-known `IndexState` (or None
        if no run has ever started). With a `target` (source id or path),
        returns a `DocumentResult` per file indexed under that source.
        Raises `SourceNotFoundError` if `target` doesn't match a registered
        source.
        """
        if target is None:
            return _read_state()

        conn = _connect()
        try:
            source = _get_source(conn, _coerce_target(target))
            return _get_document_results(conn, source.id)
        finally:
            conn.close()

    def stop(self) -> None:
        """Stop the currently running background index and wait for confirmation.

        Raises `IndexRunnerError` if no background index run is currently running.
        """
        _request_stop()

    def pause(self) -> None:
        """Pause the currently running background index.

        Raises `IndexRunnerError` if no background index run is currently running.
        """
        _request_pause()

    def resume(self) -> None:
        """Resume a paused background index run.

        Raises `IndexRunnerError` if no background index run is currently running.
        """
        _request_resume()

    def history(self, target: str | int | None = None, limit: int = 10) -> list[IndexRun]:
        """List past background index runs, most recent first, optionally filtered to one source.

        A run over "all sources" is included alongside runs targeted at
        just `target`. Raises `SourceNotFoundError` if `target` doesn't
        match a registered source.
        """
        conn = _connect()
        try:
            if target is not None:
                _get_source(conn, _coerce_target(target))
            return _list_index_runs(conn, str(target) if target is not None else None, limit)
        finally:
            conn.close()


class GPUSettings:
    """Whether OCR should attempt to use the GPU.

    Not instantiated directly — use `Vethuq().settings.gpu`.
    """

    def is_enabled(self) -> bool:
        """Whether OCR should attempt to use the GPU. Disabled by default."""
        conn = _connect()
        try:
            return _is_gpu_enabled(conn)
        finally:
            conn.close()

    def enable(self) -> None:
        """Enable GPU use for OCR.

        Only takes effect if a CUDA-capable PaddlePaddle build with a
        visible GPU is actually installed - otherwise OCR silently falls
        back to CPU.
        """
        conn = _connect()
        try:
            _set_gpu_enabled(conn, True)
        finally:
            conn.close()

    def disable(self) -> None:
        """Disable GPU use for OCR (the default) - OCR always runs on CPU."""
        conn = _connect()
        try:
            _set_gpu_enabled(conn, False)
        finally:
            conn.close()


class SnippetSettings:
    """How much context `search` shows around a match.

    Not instantiated directly — use `Vethuq().settings.search.snippet`.
    """

    def get(self) -> int:
        """How many characters of context `search` shows around a match. 80 by default."""
        conn = _connect()
        try:
            return _get_search_snippet_context_chars(conn)
        finally:
            conn.close()

    def set(self, chars: int) -> None:
        """Set how many characters of context `search` shows around a match.

        Raises `InvalidSettingValueError` if `chars` is negative.
        """
        conn = _connect()
        try:
            _set_search_snippet_context_chars(conn, chars)
        finally:
            conn.close()


class ExportFormatSettings:
    """The default format `search --export` writes to.

    Not instantiated directly — use `Vethuq().settings.search.export_format`.
    """

    def get(self) -> str:
        """Default format `search --export` writes to when none is given. 'json' by default."""
        conn = _connect()
        try:
            return _get_search_export_format(conn)
        finally:
            conn.close()

    def set(self, format_: str) -> None:
        """Set the default format `search --export` writes to when none is given.

        `format_` must be one of `SEARCH_EXPORT_FORMATS`. Raises
        `InvalidSettingValueError` otherwise.
        """
        conn = _connect()
        try:
            _set_search_export_format(conn, format_)
        finally:
            conn.close()


class SearchSettings:
    """Configure `search` behavior. Not instantiated directly — use `Vethuq().settings.search`."""

    def __init__(self) -> None:
        self.snippet = SnippetSettings()
        self.export_format = ExportFormatSettings()


class RemovedRetentionSettings:
    """How long a removed source is kept before being purged. Not instantiated directly — use
    `Vethuq().settings.index.removed_retention`."""

    def get(self) -> int:
        """Minutes a removed source is kept before it's purged from the DB. 7 days by default."""
        conn = _connect()
        try:
            return _get_removed_source_retention_minutes(conn)
        finally:
            conn.close()

    def set(self, minutes: int) -> None:
        """Set, in minutes, how long a removed source is kept before it's purged from the DB.

        Raises `InvalidSettingValueError` if `minutes` is negative.
        """
        conn = _connect()
        try:
            _set_removed_source_retention_minutes(conn, minutes)
        finally:
            conn.close()


class OcrRetrySettings:
    """How many times to retry a file's OCR after a transient failure. Not instantiated
    directly — use `Vethuq().settings.index.ocr_retry`."""

    def get(self) -> int:
        """How many times to retry a file's OCR after a transient failure. 3 by default."""
        conn = _connect()
        try:
            return _get_ocr_retry_attempts(conn)
        finally:
            conn.close()

    def set(self, attempts: int) -> None:
        """Set how many times to retry a file's OCR after a transient failure.

        Raises `InvalidSettingValueError` if `attempts` is negative.
        """
        conn = _connect()
        try:
            _set_ocr_retry_attempts(conn, attempts)
        finally:
            conn.close()


class ThreadWorkersSettings:
    """How many worker threads background indexing uses. Not instantiated directly — use
    `Vethuq().settings.index.thread_workers`."""

    AUTO = _THREAD_WORKERS_AUTO
    MAX = _THREAD_WORKERS_MAX

    def get(self) -> str:
        """How many worker threads background indexing uses. '0' (disabled) by default.

        One of '0' (disabled - sequential, single-threaded indexing),
        '1'-`MAX` (a fixed worker count), or `AUTO` (sized at run time from
        current CPU/memory headroom).
        """
        conn = _connect()
        try:
            return _get_thread_workers(conn)
        finally:
            conn.close()

    def set(self, value: str) -> None:
        """Set how many worker threads background indexing uses.

        `value` must be '0'-`MAX` or `AUTO`. Raises `InvalidSettingValueError`
        otherwise.
        """
        conn = _connect()
        try:
            _set_thread_workers(conn, value)
        finally:
            conn.close()


class StaleLockSettings:
    """Whether a stale lock is auto-cleared on the next run. Not instantiated directly — use
    `Vethuq().settings.index.stale_lock`."""

    def get(self) -> str:
        """Whether a lock left behind by a run that didn't exit cleanly is auto-cleared on
        the next run. 'auto' by default.

        One of 'auto' (auto-clear - the default), 'enable' (auto-clear - an
        explicit opt-in with the same effect as 'auto'), or 'disable'
        (require `force=True` on `Index.run`/`Index.restart`, as before).
        """
        conn = _connect()
        try:
            return _get_stale_lock(conn)
        finally:
            conn.close()

    def set(self, value: str) -> None:
        """Set whether a stale lock is auto-cleared on the next run.

        `value` must be one of `STALE_LOCK_VALUES`. Raises
        `InvalidSettingValueError` otherwise.
        """
        conn = _connect()
        try:
            _set_stale_lock(conn, value)
        finally:
            conn.close()


class OcrEngineSettings:
    """How thoroughly OCR looks for rotated text. Not instantiated directly — use
    `Vethuq().settings.index.engine`."""

    def get(self) -> str:
        """How thoroughly OCR looks for rotated text. 'quick' by default.

        One of `OCR_ENGINE_MODES`: 'quick' (upright text only), 'moderate'
        (also 90/180/270 degree rotations), or 'deep' (also every 15
        degrees). Each includes the ones before it. Files are always indexed
        'quick' first so they're searchable right away; the deeper passes
        then run in the background while indexing continues.
        """
        conn = _connect()
        try:
            return _get_ocr_engine(conn)
        finally:
            conn.close()

    def set(self, value: str) -> None:
        """Set how thoroughly OCR looks for rotated text.

        `value` must be one of `OCR_ENGINE_MODES`. Raises
        `InvalidSettingValueError` otherwise. Files already indexed are
        brought up to the new level the next time indexing runs.
        """
        conn = _connect()
        try:
            _set_ocr_engine(conn, value)
        finally:
            conn.close()


class IndexSettings:
    """Configure indexing behavior. Not instantiated directly — use `Vethuq().settings.index`."""

    def __init__(self) -> None:
        self.removed_retention = RemovedRetentionSettings()
        self.ocr_retry = OcrRetrySettings()
        self.thread_workers = ThreadWorkersSettings()
        self.stale_lock = StaleLockSettings()
        self.engine = OcrEngineSettings()


class Settings:
    """Configure VethuQ. Not instantiated directly — use `Vethuq().settings`."""

    def __init__(self) -> None:
        self.gpu = GPUSettings()
        self.search = SearchSettings()
        self.index = IndexSettings()


class Stats:
    """View and reset accumulated OCR processing/confidence statistics.

    Not instantiated directly — use `Vethuq().stats`.
    """

    def processing(self) -> list[ProcessingMetric]:
        """Return per-(phase, file_type, size_bucket) running averages of OCR processing."""
        conn = _connect()
        try:
            return _get_processing_metrics(conn)
        finally:
            conn.close()

    def confidence(self) -> list[ConfidenceMetric]:
        """Return per-(file_type, process_type) running averages of OCR confidence."""
        conn = _connect()
        try:
            return _get_confidence_metrics(conn)
        finally:
            conn.close()

    def reset(self) -> None:
        """Clear processing and confidence statistics.

        Both are running averages folded in as OCR completes, and
        `Index.run`'s ETA estimate is based on them - after a reset, ETAs
        are unavailable again until enough files have been (re)indexed to
        rebuild them.
        """
        conn = _connect()
        try:
            _reset_metrics(conn)
        finally:
            conn.close()


class Search:
    """Search previously OCR-indexed content.

    Not instantiated directly — use `Vethuq().search`.
    """

    def run(self, content: str, *, context_chars: int | None = None) -> list[SearchMatch]:
        """Search indexed OCR text for `content`, case-insensitively.

        Returns one `SearchMatch` per matching page, ordered by file path
        (pages of the same PDF stay in page order). Only successfully
        indexed documents are considered. `context_chars` defaults to
        `Vethuq().settings.search.snippet` if not given.
        """
        conn = _connect()
        try:
            return _search_indexed_content(conn, content, context_chars=context_chars)
        finally:
            conn.close()

    def export(
        self, matches: list[SearchMatch], query: str, output: str | Path, format_: str | None = None
    ) -> Path:
        """Write `matches` for `query` to `output` as JSON or HTML.

        `format_` defaults to `Vethuq().settings.search.export_format` if
        not given, and must be one of `SEARCH_EXPORT_FORMATS`.
        """
        conn = _connect()
        try:
            resolved_format = format_ if format_ is not None else _get_search_export_format(conn)
        finally:
            conn.close()
        output_path = Path(output)
        _export_search_results(matches, query, output_path, resolved_format)
        return output_path


class Vethuq:
    """Client for VethuQ's local database — the same one the CLI and desktop app use.

    ```python
    client = vethuq.Vethuq()
    client.sources.add("./path/to/folder-or-file")
    client.index.run(wait=True)
    client.settings.gpu.enable()
    client.stats.processing()
    client.search.run("invoice")
    ```
    """

    def __init__(self) -> None:
        self.sources = Sources()
        self.index = Index()
        self.settings = Settings()
        self.stats = Stats()
        self.search = Search()
