"""VethuQ — document intelligence and evidence infrastructure.

Library entry point. The `vethuq` CLI is installed separately as a console
script (see `pyproject.toml`); this module re-exports the public library
API. `vethuq._core` / `vethuq._cli` are vendored copies of the internal
`vethuq-core` / `vethuq-cli` workspace packages, generated by
`packages/vethuq/scripts/merge_sources.py` — not committed, not a public API.
"""

from collections.abc import Callable
from datetime import date
from pathlib import Path

from vethuq._core.db.backup import Backup as _Backup
from vethuq._core.db.backup import BackupError, BackupInfo
from vethuq._core.db.integrity import IntegrityCheck as _IntegrityCheck
from vethuq._core.db.integrity import IntegrityCheckResult
from vethuq._core.errors import (
    CorruptDatabaseError,
    DataFolderNotWritableError,
    InvalidConfigError,
    OcrModelMissingError,
    SchemaVersionError,
    StartupError,
)
from vethuq._core.index import (
    AlreadyRunningError,
    AmbiguousFileError,
    DatabaseIntegrityError,
    FileNotTrackedError,
    IndexRun,
    IndexRunnerError,
    IndexState,
    SearchIndexRebuildResult,
    StaleLockError,
)
from vethuq._core.index import IndexRunner as _IndexRunner
from vethuq._core.index import Reindex as _Reindex
from vethuq._core.index import SearchIndexRebuild as _SearchIndexRebuild
from vethuq._core.logs import LogNotFoundError
from vethuq._core.logs import Logs as _Logs
from vethuq._core.ocr import Document as _Document
from vethuq._core.ocr import DocumentResult
from vethuq._core.search import Export as _Export
from vethuq._core.search import PageResult, SearchMatch, SearchOptionError, SearchQueryError
from vethuq._core.search import Search as _Search
from vethuq._core.search.engines import Ranking as _Ranking
from vethuq._core.settings import DbSettings as _DbSettings
from vethuq._core.settings import GpuSettings as _GpuSettings
from vethuq._core.settings import IndexSettings as _IndexSettings
from vethuq._core.settings import (
    InvalidSettingValueError,
    SettingsError,
)
from vethuq._core.settings import LogSettings as _LogSettings
from vethuq._core.settings import OcrSettings as _OcrSettings
from vethuq._core.settings import SearchSettings as _SearchSettings
from vethuq._core.settings import SourceSettings as _SourceSettings
from vethuq._core.sources import (
    PurgeResult,
    Source,
    SourceAlreadyExistsError,
    SourceError,
    SourceFile,
    SourceNotFoundError,
    SourceNotRemovedError,
    SourcePathError,
)
from vethuq._core.sources import Sources as _Sources
from vethuq._core.stats import Confidence as _Confidence
from vethuq._core.stats import ConfidenceMetric, ProcessingMetric
from vethuq._core.stats import Processing as _Processing
from vethuq._core.stats import Stats as _Stats
from vethuq._core.storage import default_db_path as _default_db_path
from vethuq._core.storage import open_storage as _open_storage
from vethuq._core.version import VersionDetails
from vethuq._core.version import VersionInfo as _VersionInfo

DB_PATH = _default_db_path()
"""Path to VethuQ's local SQLite database (the same one the CLI and desktop app use)."""

ENGINE_BADGES = _Ranking.BADGES
ENGINE_MEANINGS = _Ranking.MEANINGS
ENGINE_TIERS = _Ranking.TIERS
OCR_ENGINE_MODES = _OcrSettings.ENGINE_MODES
SEARCH_ENGINES = _SearchSettings.ENGINES
SEARCH_EXPORT_FORMATS = _SearchSettings.EXPORT_FORMATS
SEARCH_FUZZY_PRESETS = _SearchSettings.FUZZY_PRESETS
SEARCH_PROXIMITY_PRESETS = _SearchSettings.PROXIMITY_PRESETS
SEARCH_LEETSPEAK_LEVELS = _SearchSettings.LEETSPEAK_LEVELS
SEARCH_NOISE_LEVELS = tuple(_SearchSettings.NOISE_LEVELS)
SEARCH_PROXIMITY_MAX_DISTANCE = _SearchSettings.PROXIMITY_MAX_DISTANCE
STALE_LOCK_VALUES = _IndexSettings.STALE_LOCK_VALUES
BACKUP_VALUES = _DbSettings.BACKUP_VALUES
INTEGRITY_CHECK_VALUES = _DbSettings.INTEGRITY_CHECK_VALUES
LOG_LEVEL_VALUES = _LogSettings.LEVEL_VALUES
LOG_COMPONENTS = tuple(_Logs.COMPONENTS)

engine_badge = _Ranking.engine_badge
hit_badge = _Ranking.hit_badge

__all__ = [
    "VersionDetails",
    "BACKUP_VALUES",
    "ENGINE_BADGES",
    "ENGINE_MEANINGS",
    "ENGINE_TIERS",
    "INTEGRITY_CHECK_VALUES",
    "LOG_COMPONENTS",
    "LOG_LEVEL_VALUES",
    "OCR_ENGINE_MODES",
    "SEARCH_ENGINES",
    "SEARCH_EXPORT_FORMATS",
    "SEARCH_FUZZY_PRESETS",
    "SEARCH_LEETSPEAK_LEVELS",
    "SEARCH_NOISE_LEVELS",
    "SEARCH_PROXIMITY_MAX_DISTANCE",
    "SEARCH_PROXIMITY_PRESETS",
    "STALE_LOCK_VALUES",
    "AlreadyRunningError",
    "AmbiguousFileError",
    "BackupError",
    "CorruptDatabaseError",
    "DataFolderNotWritableError",
    "InvalidConfigError",
    "OcrModelMissingError",
    "SchemaVersionError",
    "StartupError",
    "BackupInfo",
    "BackupSettings",
    "ConfidenceMetric",
    "DatabaseIntegrityError",
    "DB_PATH",
    "Db",
    "DbSettings",
    "DocumentResult",
    "ExportFormatSettings",
    "GPUSettings",
    "Index",
    "IndexRun",
    "IndexRunnerError",
    "IndexSettings",
    "IndexState",
    "IntegrityCheckResult",
    "IntegrityCheckSettings",
    "InvalidSettingValueError",
    "LogLevelSettings",
    "LogNotFoundError",
    "LogRetentionSettings",
    "Logs",
    "LogsSettings",
    "FileNotTrackedError",
    "OcrEngineSettings",
    "OcrSettings",
    "OcrRetrySettings",
    "PageResult",
    "ProcessingMetric",
    "RemovedRetentionSettings",
    "Search",
    "SearchCaseSensitiveSettings",
    "SearchEngineSettings",
    "SearchFuzzySettings",
    "SearchFuzzyThresholdSettings",
    "SearchLeetspeakLevelSettings",
    "SearchLeetspeakSettings",
    "SearchNoiseFuzzySettings",
    "SearchNoiseLevelSettings",
    "SearchIndexRebuildResult",
    "SearchMatch",
    "SearchOptionError",
    "SearchProximityDistanceSettings",
    "SearchProximitySettings",
    "SearchQueryError",
    "SearchSettings",
    "Settings",
    "PurgeResult",
    "SettingsError",
    "SnippetSettings",
    "Source",
    "SourceAlreadyExistsError",
    "SourceError",
    "SourceFile",
    "SourceNotFoundError",
    "SourceNotRemovedError",
    "SourcePathError",
    "Sources",
    "StaleLockError",
    "StabilityCheckSettings",
    "StaleLockSettings",
    "Stats",
    "ThreadWorkersSettings",
    "Vethuq",
    "engine_badge",
    "hit_badge",
]


class Sources:
    """Register and manage files/folders as OCR/indexing sources.

    Not instantiated directly — use `Vethuq().sources`.
    """

    def add(self, path: str | Path) -> Source:
        """Register a file or folder as a source. Folders are indexed recursively.

        Re-adding a path that was previously removed reactivates it instead
        of failing. Raises `SourcePathError` if `path` doesn't exist, and
        `SourceAlreadyExistsError` if it's already an active source.
        """
        storage = _open_storage()
        try:
            return _Sources.add(storage, path)
        finally:
            storage.close()

    # Defined before `list` below, whose name would otherwise shadow the builtin in annotations.
    def files(self, path_or_id: str | Path | int) -> list[SourceFile]:
        """Return the files tracked under a source, by id or path, ordered by file path.

        Each `SourceFile` carries its id, status and the same detail
        `vethuq source list <source> --detail` shows. Raises
        `SourceNotFoundError` if no active source matches.
        """
        storage = _open_storage()
        try:
            return _Sources.list_files(storage, path_or_id)
        finally:
            storage.close()

    def list(self, include_inactive: bool = False) -> list[Source]:
        """Return registered sources, most recently added first."""
        storage = _open_storage()
        try:
            return _Sources.list_all(storage, include_inactive)
        finally:
            storage.close()

    def remove(self, path_or_id: str | Path | int) -> Source:
        """Unregister a source by id or path. Raises `SourceNotFoundError` if it doesn't exist."""
        storage = _open_storage()
        try:
            return _Sources.remove(storage, path_or_id)
        finally:
            storage.close()

    def purge(self, path_or_id: str | Path | int) -> PurgeResult:
        """Permanently delete a removed source (by id or path) or a removed file (by path).

        Works whether or not the retention period has passed, and deletes the
        indexed data too. Raises `SourceNotRemovedError` if the source or file is
        still active, and `SourceNotFoundError` if nothing matches.
        """
        storage = _open_storage()
        try:
            return _Sources.purge(storage, _Sources.coerce(path_or_id))
        finally:
            storage.close()


class Index:
    """Run and control background OCR indexing over registered sources.

    Not instantiated directly — use `Vethuq().index`.
    """

    def run(
        self, target: str | int | None = None, *, force: bool = False, wait: bool = False
    ) -> int | IndexState | None:
        """Start OCR indexing on registered sources in the background.

        A source that's already fully indexed is still checked for files
        added or modified since the last run; unchanged files are left
        untouched. Returns the background process id, or, if `wait` is
        True, blocks until the run finishes and returns its final
        `IndexState` instead.

        Raises `AlreadyRunningError` if a run is already in progress, and
        `StaleLockError` if a previous run left a stale lock (`force=True`
        clears it). Raises `SourceNotFoundError` if `target` doesn't match a
        registered source.
        """
        pid = _IndexRunner.start_run(
            str(target) if target is not None else None, force=force, restart=False
        )
        return _IndexRunner.wait(pid) if wait else pid

    def restart(
        self, target: str | int | None = None, *, force: bool = False, wait: bool = False
    ) -> int | IndexState | None:
        """Retry only previously-failed files, in the background. See `run`."""
        pid = _IndexRunner.start_run(
            str(target) if target is not None else None, force=force, restart=True
        )
        return _IndexRunner.wait(pid) if wait else pid

    def reindex(
        self, target: str | int, *, force: bool = False, wait: bool = False
    ) -> int | IndexState | None:
        """Re-index every file under a source (id or path), not just failed ones.

        Files are OCR'd again and their existing documents updated in place, so
        nothing is duplicated. Same errors and return value as `run`.
        """
        pid = _Reindex.start_source(target, force=force)
        return _IndexRunner.wait(pid) if wait else pid

    def reindex_file(
        self,
        file: str | int,
        *,
        source: str | int | None = None,
        force: bool = False,
        wait: bool = False,
    ) -> int | IndexState | None:
        """Re-index one file, given its document id or path.

        Raises `FileNotTrackedError` if the file isn't tracked, and
        `AmbiguousFileError` if it sits under more than one source and `source`
        (id or path) isn't given. Otherwise like `run`.
        """
        pid = _Reindex.start_file(file, source=source, force=force)
        return _IndexRunner.wait(pid) if wait else pid

    def rebuild_search(
        self, *, on_progress: Callable[[str, int, int], None] | None = None
    ) -> SearchIndexRebuildResult:
        """Rebuild the full-text search tables from the page text already stored.

        No file is re-read or re-OCR'd. `on_progress(index, position, total)` is
        called before each table is rebuilt. A table that fails is reported in the
        result's `failed` and the others still rebuild. Raises `AlreadyRunningError`
        while an index run is active.
        """
        return _SearchIndexRebuild.run(on_progress=on_progress)

    def status(self, target: str | int | None = None) -> IndexState | list[DocumentResult] | None:
        """Show background index run progress, or per-file detail for one source.

        With no `target`, returns the live/last-known `IndexState` (or None
        if no run has ever started). With a `target` (source id or path),
        returns a `DocumentResult` per file indexed under that source.
        Raises `SourceNotFoundError` if `target` doesn't match a registered
        source.
        """
        if target is None:
            return _IndexRunner.read_state()

        storage = _open_storage()
        try:
            source = _Sources.get(storage, _Sources.coerce(target))
            return _Document.get_results(storage, source.id)
        finally:
            storage.close()

    def stop(self) -> None:
        """Stop the currently running background index and wait for confirmation.

        Raises `IndexRunnerError` if no background index run is currently running.
        """
        _IndexRunner.request_stop()

    def pause(self) -> None:
        """Pause the currently running background index.

        Raises `IndexRunnerError` if no background index run is currently running.
        """
        _IndexRunner.request_pause()

    def resume(self) -> None:
        """Resume a paused background index run.

        Raises `IndexRunnerError` if no background index run is currently running.
        """
        _IndexRunner.request_resume()

    def history(self, target: str | int | None = None, limit: int = 10) -> list[IndexRun]:
        """List past background index runs, most recent first, optionally filtered to one source.

        A run over "all sources" is included alongside runs targeted at
        just `target`. Raises `SourceNotFoundError` if `target` doesn't
        match a registered source.
        """
        storage = _open_storage()
        try:
            if target is not None:
                _Sources.get(storage, _Sources.coerce(target))
            return _IndexRunner.list_runs(
                storage, str(target) if target is not None else None, limit
            )
        finally:
            storage.close()


class GPUSettings:
    """Whether OCR should attempt to use the GPU.

    Not instantiated directly — use `Vethuq().settings.gpu`.
    """

    def is_enabled(self) -> bool:
        """Whether OCR should attempt to use the GPU. Disabled by default."""
        storage = _open_storage()
        try:
            return _GpuSettings.is_enabled(storage)
        finally:
            storage.close()

    def enable(self) -> None:
        """Enable GPU use for OCR.

        Only takes effect if a CUDA-capable PaddlePaddle build with a
        visible GPU is actually installed - otherwise OCR silently falls
        back to CPU.
        """
        storage = _open_storage()
        try:
            _GpuSettings.set_enabled(storage, True)
        finally:
            storage.close()

    def disable(self) -> None:
        """Disable GPU use for OCR (the default) - OCR always runs on CPU."""
        storage = _open_storage()
        try:
            _GpuSettings.set_enabled(storage, False)
        finally:
            storage.close()


class SnippetSettings:
    """How much context `search` shows around a match.

    Not instantiated directly — use `Vethuq().settings.search.snippet`.
    """

    def get(self) -> int:
        """How many characters of context `search` shows around a match. 80 by default."""
        storage = _open_storage()
        try:
            return _SearchSettings.get_snippet_context_chars(storage)
        finally:
            storage.close()

    def set(self, chars: int) -> None:
        """Set how many characters of context `search` shows around a match.

        Raises `InvalidSettingValueError` if `chars` is negative.
        """
        storage = _open_storage()
        try:
            _SearchSettings.set_snippet_context_chars(storage, chars)
        finally:
            storage.close()


class ExportFormatSettings:
    """The default format `search --export` writes to.

    Not instantiated directly — use `Vethuq().settings.search.export_format`.
    """

    def get(self) -> str:
        """Default format `search --export` writes to when none is given. 'json' by default."""
        storage = _open_storage()
        try:
            return _SearchSettings.get_export_format(storage)
        finally:
            storage.close()

    def set(self, format_: str) -> None:
        """Set the default format `search --export` writes to when none is given.

        `format_` must be one of `SEARCH_EXPORT_FORMATS`. Raises
        `InvalidSettingValueError` otherwise.
        """
        storage = _open_storage()
        try:
            _SearchSettings.set_export_format(storage, format_)
        finally:
            storage.close()


class SearchEngineSettings:
    """The default engine `search` matches with.

    Not instantiated directly — use `Vethuq().settings.search.engine`.
    """

    def get(self) -> str:
        """Default engine `search` uses when none is given. 'like' by default."""
        storage = _open_storage()
        try:
            return _SearchSettings.get_engine(storage)
        finally:
            storage.close()

    def set(self, engine: str) -> None:
        """Set the default engine `search` uses when none is given.

        `engine` must be one of `SEARCH_ENGINES`; raises `InvalidSettingValueError` otherwise.
        """
        storage = _open_storage()
        try:
            _SearchSettings.set_engine(storage, engine)
        finally:
            storage.close()


class SearchCaseSensitiveSettings:
    """Whether `search` matches case by default (only the 'like' and 'fuzzy' engines honour it).

    Not instantiated directly — use `Vethuq().settings.search.case_sensitive`.
    """

    def get(self) -> bool:
        """Whether `search` matches case-sensitively by default. `False` by default."""
        storage = _open_storage()
        try:
            return _SearchSettings.is_case_sensitive(storage)
        finally:
            storage.close()

    def set(self, enabled: bool) -> None:
        """Set whether `search` matches case-sensitively by default."""
        storage = _open_storage()
        try:
            _SearchSettings.set_case_sensitive(storage, enabled)
        finally:
            storage.close()


class SearchFuzzyThresholdSettings:
    """How close a word must be to the query for `fuzzy` search to match it.

    Not instantiated directly — use `Vethuq().settings.search.fuzzy.threshold`.
    """

    def get(self) -> str:
        """The stored threshold, as set: a name from `SEARCH_FUZZY_PRESETS`, or a percentage
        or similarity as text (e.g. `"75%"`). `"balanced"` by default."""
        storage = _open_storage()
        try:
            return _SearchSettings.get_fuzzy_threshold_setting(storage)
        finally:
            storage.close()

    def set(self, threshold: str | float) -> None:
        """Set the default threshold: a name from `SEARCH_FUZZY_PRESETS` (`"strict"` 90%,
        `"balanced"` 80%, `"loose"` 65%), a percentage (`"75%"`, or a whole number such as
        `75`) or a similarity above 0 and up to 1 (`0.75`).

        Raises `InvalidSettingValueError` for anything else.
        """
        storage = _open_storage()
        try:
            _SearchSettings.set_fuzzy_threshold(storage, str(threshold))
        finally:
            storage.close()


class SearchFuzzySettings:
    """Configure the `fuzzy` search engine. Not instantiated directly — use
    `Vethuq().settings.search.fuzzy`."""

    def __init__(self) -> None:
        self.threshold = SearchFuzzyThresholdSettings()


class SearchProximityDistanceSettings:
    """How many words may separate a `proximity` search's first and last term.

    Not instantiated directly — use `Vethuq().settings.search.proximity.distance`.
    """

    def get(self) -> str:
        """The stored distance, as set: a name from `SEARCH_PROXIMITY_PRESETS` or a number
        of words as text. `"medium"` (10 words) by default."""
        storage = _open_storage()
        try:
            return _SearchSettings.get_proximity_distance_setting(storage)
        finally:
            storage.close()

    def set(self, distance: str | int) -> None:
        """Set the default distance: a name from `SEARCH_PROXIMITY_PRESETS` (`"tight"` 3 words,
        `"medium"` 10, `"loose"` 30) or a number of words from 1 to
        `SEARCH_PROXIMITY_MAX_DISTANCE`.

        Raises `InvalidSettingValueError` for anything else.
        """
        storage = _open_storage()
        try:
            _SearchSettings.set_proximity_distance(storage, str(distance))
        finally:
            storage.close()


class SearchProximitySettings:
    """Configure the `proximity` search engine. Not instantiated directly — use
    `Vethuq().settings.search.proximity`."""

    def __init__(self) -> None:
        self.distance = SearchProximityDistanceSettings()


class SearchLeetspeakLevelSettings:
    """Which look-alike characters `leetspeak` search recognizes.

    Not instantiated directly — use `Vethuq().settings.search.leetspeak.level`.
    """

    def get(self) -> str:
        """The stored level, a name from `SEARCH_LEETSPEAK_LEVELS`. `"basic"` by default."""
        storage = _open_storage()
        try:
            return _SearchSettings.get_leetspeak_level(storage)
        finally:
            storage.close()

    def set(self, level: str) -> None:
        """Set the default level: `"basic"` (0 1 3 4 5 7 @ $), `"standard"` (adds 2 6 8 9 + ! |)
        or `"extended"` (adds multi-character forms such as `|\\|` for n and `ph` for f). Each
        level includes the one before it.

        Raises `InvalidSettingValueError` for anything else.
        """
        storage = _open_storage()
        try:
            _SearchSettings.set_leetspeak_level(storage, level)
        finally:
            storage.close()


class SearchLeetspeakSettings:
    """Configure the `leetspeak` search engine. Not instantiated directly — use
    `Vethuq().settings.search.leetspeak`."""

    def __init__(self) -> None:
        self.level = SearchLeetspeakLevelSettings()


class SearchNoiseLevelSettings:
    """How much stray punctuation and whitespace `noise-fuzzy` search skips inside a match.

    Not instantiated directly — use `Vethuq().settings.search.noise_fuzzy.noise`.
    """

    def get(self) -> str:
        """The stored level, a name from `SEARCH_NOISE_LEVELS`. `"low"` by default."""
        storage = _open_storage()
        try:
            return _SearchSettings.get_noise_level(storage)
        finally:
            storage.close()

    def set(self, level: str) -> None:
        """Set the default level: `"low"` (at most 1 noise character in a row, 2 in all),
        `"medium"` (3 in a row, 6 in all) or `"high"` (6 in a row, 12 in all).

        Raises `InvalidSettingValueError` for anything else.
        """
        storage = _open_storage()
        try:
            _SearchSettings.set_noise_level(storage, level)
        finally:
            storage.close()


class SearchNoiseFuzzySettings:
    """Configure the `noise-fuzzy` search engine. Not instantiated directly — use
    `Vethuq().settings.search.noise_fuzzy`."""

    def __init__(self) -> None:
        self.noise = SearchNoiseLevelSettings()


class SearchSettings:
    """Configure `search` behavior. Not instantiated directly — use `Vethuq().settings.search`."""

    def __init__(self) -> None:
        self.snippet = SnippetSettings()
        self.export_format = ExportFormatSettings()
        self.engine = SearchEngineSettings()
        self.case_sensitive = SearchCaseSensitiveSettings()
        self.fuzzy = SearchFuzzySettings()
        self.proximity = SearchProximitySettings()
        self.leetspeak = SearchLeetspeakSettings()
        self.noise_fuzzy = SearchNoiseFuzzySettings()


class RemovedRetentionSettings:
    """How long a removed source is kept before being purged. Not instantiated directly — use
    `Vethuq().settings.index.removed_retention`."""

    def get(self) -> int:
        """Minutes a removed source is kept before it's purged from the DB. 7 days by default."""
        storage = _open_storage()
        try:
            return _SourceSettings.get_removed_retention_minutes(storage)
        finally:
            storage.close()

    def set(self, minutes: int) -> None:
        """Set, in minutes, how long a removed source is kept before it's purged from the DB.

        Raises `InvalidSettingValueError` if `minutes` is negative.
        """
        storage = _open_storage()
        try:
            _SourceSettings.set_removed_retention_minutes(storage, minutes)
        finally:
            storage.close()


class OcrRetrySettings:
    """How many times to retry a file's OCR after a transient failure. Not instantiated
    directly — use `Vethuq().settings.ocr.retry`."""

    def get(self) -> int:
        """How many times to retry a file's OCR after a transient failure. 3 by default."""
        storage = _open_storage()
        try:
            return _OcrSettings.get_retry_attempts(storage)
        finally:
            storage.close()

    def set(self, attempts: int) -> None:
        """Set how many times to retry a file's OCR after a transient failure.

        Raises `InvalidSettingValueError` if `attempts` is negative.
        """
        storage = _open_storage()
        try:
            _OcrSettings.set_retry_attempts(storage, attempts)
        finally:
            storage.close()


class ThreadWorkersSettings:
    """How many worker threads background indexing uses. Not instantiated directly — use
    `Vethuq().settings.index.thread_workers`."""

    AUTO = _IndexSettings.THREAD_WORKERS_AUTO
    MAX = _IndexSettings.THREAD_WORKERS_MAX

    def get(self) -> str:
        """How many worker threads background indexing uses. '0' (disabled) by default.

        One of '0' (disabled - sequential, single-threaded indexing),
        '1'-`MAX` (a fixed worker count), or `AUTO` (sized at run time from
        current CPU/memory headroom).
        """
        storage = _open_storage()
        try:
            return _IndexSettings.get_thread_workers(storage)
        finally:
            storage.close()

    def set(self, value: str) -> None:
        """Set how many worker threads background indexing uses.

        `value` must be '0'-`MAX` or `AUTO`. Raises `InvalidSettingValueError`
        otherwise.
        """
        storage = _open_storage()
        try:
            _IndexSettings.set_thread_workers(storage, value)
        finally:
            storage.close()


class StabilityCheckSettings:
    """How long a file must stay unchanged before it's indexed. Not instantiated
    directly — use `Vethuq().settings.index.stability_check`."""

    def get(self) -> float:
        """Seconds between the two checks that a file has stopped changing. 1 by
        default; 0 disables the check."""
        storage = _open_storage()
        try:
            return _OcrSettings.get_stability_check_seconds(storage)
        finally:
            storage.close()

    def set(self, seconds: float) -> None:
        """Set the seconds between the two checks that a file has stopped changing.

        Raises `InvalidSettingValueError` if `seconds` is negative.
        """
        storage = _open_storage()
        try:
            _OcrSettings.set_stability_check_seconds(storage, seconds)
        finally:
            storage.close()


class StaleLockSettings:
    """Whether a stale lock is auto-cleared on the next run. Not instantiated directly — use
    `Vethuq().settings.index.stale_lock`."""

    def get(self) -> str:
        """Whether a lock left behind by a run that didn't exit cleanly is auto-cleared on
        the next run. 'auto' by default.

        One of 'auto' (auto-clear - the default), 'enable' (auto-clear - an
        explicit opt-in with the same effect as 'auto'), or 'disable'
        (require `force=True` on `Index.run`/`Index.restart`, as before).
        """
        storage = _open_storage()
        try:
            return _IndexSettings.get_stale_lock(storage)
        finally:
            storage.close()

    def set(self, value: str) -> None:
        """Set whether a stale lock is auto-cleared on the next run.

        `value` must be one of `STALE_LOCK_VALUES`. Raises
        `InvalidSettingValueError` otherwise.
        """
        storage = _open_storage()
        try:
            _IndexSettings.set_stale_lock(storage, value)
        finally:
            storage.close()


class OcrEngineSettings:
    """How thoroughly OCR looks for rotated text. Not instantiated directly — use
    `Vethuq().settings.ocr.engine`."""

    def get(self) -> str:
        """How thoroughly OCR looks for rotated text. 'quick' by default.

        One of `OCR_ENGINE_MODES`: 'quick' (upright text only), 'moderate'
        (also 90/180/270 degree rotations), or 'deep' (also every 15
        degrees). Each includes the ones before it. Files are always indexed
        'quick' first so they're searchable right away; the deeper passes
        then run in the background while indexing continues.
        """
        storage = _open_storage()
        try:
            return _OcrSettings.get_engine(storage)
        finally:
            storage.close()

    def set(self, value: str) -> None:
        """Set how thoroughly OCR looks for rotated text.

        `value` must be one of `OCR_ENGINE_MODES`. Raises
        `InvalidSettingValueError` otherwise. Files already indexed are
        brought up to the new level the next time indexing runs.
        """
        storage = _open_storage()
        try:
            _OcrSettings.set_engine(storage, value)
        finally:
            storage.close()


class IntegrityCheckSettings:
    """Whether `PRAGMA integrity_check` runs automatically when the database is opened.
    Not instantiated directly — use `Vethuq().settings.db.integrity_check`."""

    def get(self) -> str:
        """Whether the check runs automatically when the database is opened. 'auto' by default.

        One of 'auto' (run at most once per `get_interval_minutes()` - the
        default), 'enable' (run on every connection), or 'disable' (never
        run automatically - only via `Db.integrity_check`).
        """
        storage = _open_storage()
        try:
            return _DbSettings.get_integrity_check(storage)
        finally:
            storage.close()

    def set(self, value: str) -> None:
        """Set whether the check runs automatically when the database is opened.

        `value` must be one of `INTEGRITY_CHECK_VALUES`. Raises
        `InvalidSettingValueError` otherwise.
        """
        storage = _open_storage()
        try:
            _DbSettings.set_integrity_check(storage, value)
        finally:
            storage.close()

    def get_interval_minutes(self) -> int:
        """Minutes between automatic integrity checks when `get()` is 'auto'. 1 day by default."""
        storage = _open_storage()
        try:
            return _DbSettings.get_integrity_check_interval_minutes(storage)
        finally:
            storage.close()

    def set_interval_minutes(self, minutes: int) -> None:
        """Set, in minutes, how often automatic integrity checks run when `get()` is 'auto'.

        Raises `InvalidSettingValueError` if `minutes` is negative.
        """
        storage = _open_storage()
        try:
            _DbSettings.set_integrity_check_interval_minutes(storage, minutes)
        finally:
            storage.close()


class BackupSettings:
    """Whether a compressed database backup is taken automatically when the database is opened.
    Not instantiated directly — use `Vethuq().settings.db.backup`."""

    def get(self) -> str:
        """'enable' (the default) or 'disable' (only `Db.backup_create` takes backups)."""
        storage = _open_storage()
        try:
            return _DbSettings.get_backup(storage)
        finally:
            storage.close()

    def set(self, value: str) -> None:
        """Enable or disable automatic backups; `value` must be one of `BACKUP_VALUES`.

        Raises `InvalidSettingValueError` otherwise.
        """
        storage = _open_storage()
        try:
            _DbSettings.set_backup(storage, value)
        finally:
            storage.close()

    def get_interval_minutes(self) -> int:
        """Minutes between automatic backups. 1 day by default."""
        storage = _open_storage()
        try:
            return _DbSettings.get_backup_interval_minutes(storage)
        finally:
            storage.close()

    def set_interval_minutes(self, minutes: int) -> None:
        """Set, in minutes, how often automatic backups are taken (at least 1)."""
        storage = _open_storage()
        try:
            _DbSettings.set_backup_interval_minutes(storage, minutes)
        finally:
            storage.close()

    def get_retention_days(self) -> int:
        """Days automatic backups are kept before being pruned. 7 by default."""
        storage = _open_storage()
        try:
            return _DbSettings.get_backup_retention_days(storage)
        finally:
            storage.close()

    def set_retention_days(self, days: int) -> None:
        """Set how many days automatic backups are kept (at least 1)."""
        storage = _open_storage()
        try:
            _DbSettings.set_backup_retention_days(storage, days)
        finally:
            storage.close()


class LogLevelSettings:
    """Verbosity of VethuQ's log files. Not instantiated directly — use
    `Vethuq().settings.logs.level`."""

    def get(self) -> str:
        """The log level: 'debug', 'info' (the default), 'warning' or 'error'."""
        storage = _open_storage()
        try:
            return _LogSettings.get_level(storage)
        finally:
            storage.close()

    def set(self, value: str) -> None:
        """Set the log level.

        `value` must be one of `LOG_LEVEL_VALUES`. Raises `InvalidSettingValueError`
        otherwise.
        """
        storage = _open_storage()
        try:
            _LogSettings.set_level(storage, value)
        finally:
            storage.close()


class LogRetentionSettings:
    """How many days of daily log files are kept. Not instantiated directly — use
    `Vethuq().settings.logs.retention`."""

    def get(self) -> int:
        """Days of log files kept. 15 by default."""
        storage = _open_storage()
        try:
            return _LogSettings.get_retention_days(storage)
        finally:
            storage.close()

    def set(self, days: int) -> None:
        """Set the days of log files kept.

        Raises `InvalidSettingValueError` if `days` is less than 1.
        """
        storage = _open_storage()
        try:
            _LogSettings.set_retention_days(storage, days)
        finally:
            storage.close()


class LogsSettings:
    """Configure logging. Not instantiated directly — use `Vethuq().settings.logs`."""

    def __init__(self) -> None:
        self.level = LogLevelSettings()
        self.retention = LogRetentionSettings()


class DbSettings:
    """Configure database behavior. Not instantiated directly — use `Vethuq().settings.db`."""

    def __init__(self) -> None:
        self.integrity_check = IntegrityCheckSettings()
        self.backup = BackupSettings()


class OcrSettings:
    """Configure OCR behavior. Not instantiated directly — use `Vethuq().settings.ocr`."""

    def __init__(self) -> None:
        self.retry = OcrRetrySettings()
        self.engine = OcrEngineSettings()


class IndexSettings:
    """Configure indexing behavior. Not instantiated directly — use `Vethuq().settings.index`."""

    def __init__(self) -> None:
        self.removed_retention = RemovedRetentionSettings()
        self.stability_check = StabilityCheckSettings()
        self.thread_workers = ThreadWorkersSettings()
        self.stale_lock = StaleLockSettings()


class Settings:
    """Configure VethuQ. Not instantiated directly — use `Vethuq().settings`."""

    def __init__(self) -> None:
        self.gpu = GPUSettings()
        self.search = SearchSettings()
        self.index = IndexSettings()
        self.ocr = OcrSettings()
        self.db = DbSettings()
        self.logs = LogsSettings()


class Stats:
    """View and reset accumulated OCR processing/confidence statistics.

    Not instantiated directly — use `Vethuq().stats`.
    """

    def processing(self) -> list[ProcessingMetric]:
        """Return per-(phase, file_type, size_bucket) running averages of OCR processing."""
        storage = _open_storage()
        try:
            return _Processing.get_metrics(storage)
        finally:
            storage.close()

    def confidence(self) -> list[ConfidenceMetric]:
        """Return per-(file_type, process_type) running averages of OCR confidence."""
        storage = _open_storage()
        try:
            return _Confidence.get_metrics(storage)
        finally:
            storage.close()

    def reset(self) -> None:
        """Clear processing and confidence statistics.

        Both are running averages folded in as OCR completes, and
        `Index.run`'s ETA estimate is based on them - after a reset, ETAs
        are unavailable again until enough files have been (re)indexed to
        rebuild them.
        """
        storage = _open_storage()
        try:
            _Stats.reset(storage)
        finally:
            storage.close()


class Search:
    """Search previously OCR-indexed content.

    Not instantiated directly — use `Vethuq().search`.
    """

    def run(
        self,
        content: str,
        *,
        context_chars: int | None = None,
        engine: str | None = None,
        case_sensitive: bool | None = None,
        threshold: float | str | None = None,
        distance: int | str | None = None,
        leet_level: str | None = None,
        noise: str | None = None,
    ) -> list[SearchMatch]:
        """Search indexed OCR text for `content`.

        Returns one `SearchMatch` per occurrence, ordered by file path
        (pages of the same PDF stay in page order, occurrences within a
        page in text order) - or best match first for the `full-text`, `fuzzy`, `proximity`,
        `leetspeak` and `noise-fuzzy` engines. Only successfully indexed documents are considered.
        `context_chars` defaults to `Vethuq().settings.search.snippet` if not given.

        `engine` is one of `SEARCH_ENGINES` and defaults to
        `Vethuq().settings.search.engine`: `like` finds `content` anywhere,
        even inside a word, ignoring case; `exact` finds it as typed - same
        case, as a whole word; `full-text` finds pages containing its words
        (any case, English word forms such as plurals; quote a "phrase", end
        a word with * for a prefix), best matches first; `fuzzy` finds words
        close to `content`'s - typos and OCR misreads such as `Musuem` or
        `Museurn` for `Museum` - closest first (words under 4 letters and
        anything with a digit must match exactly); `leetspeak` finds `content`'s words
        written with look-alike characters - `h3ll0` or `p@55w0rd` for `hello` or
        `password`, and the other way round - as whole words, spelled-as-typed first
        (`leet_level`, one of `SEARCH_LEETSPEAK_LEVELS`, picks which substitutions count and
        defaults to `Vethuq().settings.search.leetspeak.level`; it needs
        at least 3 characters, one a letter); `noise-fuzzy` finds `content`'s characters
        hidden by stray punctuation or whitespace (letters are never noise), look-alike
        symbols and typos at once - `h..e llo`, `h @ 3 l l 0` and `helo` for `hello` - closest
        first (it uses `threshold` and `leet_level` too, and `noise`, one of
        `SEARCH_NOISE_LEVELS`, says how much noise is skipped, defaulting to
        `Vethuq().settings.search.noise_fuzzy.noise`). `case_sensitive`
        defaults to `Vethuq().settings.search.case_sensitive` and only `like`,
        `fuzzy`, `leetspeak` and `noise-fuzzy` act on it - `exact` is always case-sensitive and
        `full-text` and `proximity` never are. `threshold` (`fuzzy` and `noise-fuzzy` only)
        is the minimum similarity between `content`'s words and the words found: a
        name from `SEARCH_FUZZY_PRESETS`, a percentage (`"80%"`) or a number above 0
        and up to 1, defaulting to `Vethuq().settings.search.fuzzy.threshold`.
        `proximity` finds passages where all of `content`'s terms - at least two words
        or `"quoted phrases"`, in any order - sit within `distance` words of each other
        (`distance` is the most words between the first and last term): a name from
        `SEARCH_PROXIMITY_PRESETS` or a number from 1 to `SEARCH_PROXIMITY_MAX_DISTANCE`,
        defaulting to `Vethuq().settings.search.proximity.distance`; one
        `SearchMatch` per passage. `engine="all"` - the default, unless
        `Vethuq().settings.search.engine` says otherwise - runs every engine and returns
        the hits in ranked page order, each labelled with the engine that found it
        (see `run_pages` for them grouped by page); the options above then reach
        the engines that can use them and are never rejected. Raises `SearchOptionError`
        for an unknown engine, an invalid `threshold`, `distance`, `leet_level` or `noise`, or an
        explicit `case_sensitive`, `threshold`, `distance`, `leet_level` or `noise` the engine
        can't honour, and
        `SearchQueryError` for a `proximity` query of fewer than two terms.
        """
        storage = _open_storage()
        try:
            options = _Search.resolve_options(
                storage, engine, case_sensitive, threshold, distance, leet_level, noise
            )
            return _Search.indexed_content(
                storage,
                content,
                context_chars=context_chars,
                engine=options.engine,
                case_sensitive=options.case_sensitive,
                threshold=options.threshold,
                distance=options.distance,
                level=options.level,
                noise=options.noise,
            )
        finally:
            storage.close()

    def run_pages(
        self,
        content: str,
        *,
        context_chars: int | None = None,
        case_sensitive: bool | None = None,
        threshold: float | str | None = None,
        distance: int | str | None = None,
        leet_level: str | None = None,
        noise: str | None = None,
    ) -> list[PageResult]:
        """Search with every engine at once and return the pages found, best first.

        Each page is one `PageResult` - however many engines found it - ranked by the
        strictest engine that did: Exact, Contains, Relevant, Near, Word, Lookalike, Similar,
        then Obscured (see `ENGINE_TIERS` and `ENGINE_BADGES`, and `engine_badge`/`hit_badge`
        for the labels the CLI and the UI show), and within a tier by that engine's own signal.
        `PageResult.engine` is the page's strictest engine and `matched_by` all of
        them; its `hits` are `SearchMatch`es best first, each with its own `engine`
        and `matched_by` (hits found by several engines are merged into one).

        `case_sensitive`, `threshold`, `distance`, `leet_level` and `noise` default to their
        settings and reach the engines that can use them (`like`/`fuzzy`/`leetspeak`/
        `noise-fuzzy`, `fuzzy`/`noise-fuzzy`, `proximity`, `leetspeak`/`noise-fuzzy`,
        `noise-fuzzy`);
        `proximity` is skipped for a query of fewer than two terms.
        `context_chars` defaults to `Vethuq().settings.search.snippet`. Raises
        `SearchOptionError` for an invalid `threshold`, `distance`, `leet_level` or `noise`.
        This is what `run` does when `engine="all"` (the default), with the hits flattened.
        """
        storage = _open_storage()
        try:
            options = _Search.resolve_options(
                storage, "all", case_sensitive, threshold, distance, leet_level, noise
            )
            return _Search.indexed_pages(
                storage,
                content,
                context_chars=context_chars,
                case_sensitive=options.case_sensitive,
                threshold=options.threshold,
                distance=options.distance,
                level=options.level,
                noise=options.noise,
            )
        finally:
            storage.close()

    def export(
        self,
        matches: list[SearchMatch],
        query: str,
        output: str | Path,
        format_: str | None = None,
        *,
        engine: str | None = None,
        case_sensitive: bool = False,
        threshold: float | None = None,
        distance: int | None = None,
        leet_level: str | None = None,
        noise: str | None = None,
    ) -> Path:
        """Write `matches` for `query` to `output` as JSON or HTML.

        `format_` defaults to `Vethuq().settings.search.export_format` if
        not given, and must be one of `SEARCH_EXPORT_FORMATS`. Pass the
        `engine`, `case_sensitive` and (for `fuzzy` or
        `proximity`) `threshold` or `distance`, (for `leetspeak`) `leet_level`, or (for
        `noise-fuzzy`) `noise` the search ran with to record them
        in the file.
        """
        storage = _open_storage()
        try:
            resolved_format = _SearchSettings.resolve_export_format(storage, format_)
        finally:
            storage.close()
        output_path = Path(output)
        _Export.search_results(
            matches,
            query,
            output_path,
            resolved_format,
            engine=engine,
            case_sensitive=case_sensitive,
            threshold=threshold,
            distance=distance,
            level=leet_level,
            noise=noise,
        )
        return output_path


class Logs:
    """Read VethuQ's log files.

    Not instantiated directly — use `Vethuq().logs`.
    """

    def tail(
        self,
        component: str,
        lines: int = 40,
        *,
        level: str | None = None,
        day: date | None = None,
    ) -> list[str]:
        """The most recent `lines` entries of a component's log, oldest first.

        `component` is one of `LOG_COMPONENTS` (`"database"`, `"index"`, `"ui"`,
        `"cli"`). `level` keeps only entries at or above it (one of
        `LOG_LEVEL_VALUES`); `day` reads that day's rotated log instead of
        today's. An entry is one log line plus any traceback lines under it.

        Raises `LogNotFoundError` if there is no log for that day and
        `ValueError` for an unknown component or level, or `lines` below 1.
        """
        return _Logs.tail(component, _default_db_path(), lines=lines, level=level, day=day)


class Db:
    """Database maintenance. Not instantiated directly — use `Vethuq().db`."""

    def integrity_check(self) -> IntegrityCheckResult:
        """Run `PRAGMA integrity_check` now and return the result.

        Also logged via the standard `logging` module (info on success,
        error with the specific corruption messages on failure). See
        `Vethuq().settings.db.integrity_check` to control whether this
        also runs automatically when the database is opened.
        """
        storage = _open_storage()
        try:
            return _IntegrityCheck.run(storage)
        finally:
            storage.close()

    def backup_create(self, name: str | None = None) -> BackupInfo:
        """Take a compressed backup of the database now and return it.

        A named snapshot is never deleted automatically. Raises `BackupError` if the
        name is invalid or taken, or the database fails its integrity check.
        """
        return _Backup.create(_default_db_path(), name)

    def backup_list(self) -> list[BackupInfo]:
        """Every database backup, newest first."""
        return _Backup.entries(_default_db_path())

    def backup_delete(self, name: str) -> None:
        """Delete one backup by name. Raises `BackupError` if there is none."""
        _Backup.delete(_default_db_path(), name)

    def restore(self, name_or_path: str) -> BackupInfo | None:
        """Replace the database with a backup (by name, or the path of a `.db.gz` file).

        The backup is verified first, and the current database is saved as a
        'safety' backup, which is returned. Raises `BackupError` on any problem,
        or `IndexRunnerError` if an index run is active.
        """
        self._require_idle()
        return _Backup.restore(_default_db_path(), name_or_path)

    def reset(self) -> BackupInfo | None:
        """Delete the database and all its data (a fresh one is created on next use).

        The current database is saved as a 'safety' backup first, which is returned.
        Raises `IndexRunnerError` if an index run is active.
        """
        self._require_idle()
        return _Backup.reset(_default_db_path())

    def repair(self) -> IntegrityCheckResult:
        """Rebuild the database's indexes (`REINDEX`) and return the fresh integrity result.

        Fixes index-only corruption; if `ok` is still False, restore a backup or
        reset. Raises `IndexRunnerError` if an index run is active.
        """
        self._require_idle()
        result, _ = _Backup.repair(_default_db_path())
        return result

    @staticmethod
    def _require_idle() -> None:
        if _IndexRunner.is_running(_default_db_path())[0]:
            raise IndexRunnerError("An index run is in progress; stop it first.")


class Vethuq:
    """Client for VethuQ's local database — the same one the CLI and desktop app use.

    ```python
    client = vethuq.Vethuq()
    client.sources.add("./path/to/folder-or-file")
    client.index.run(wait=True)
    client.settings.gpu.enable()
    client.stats.processing()
    client.search.run("invoice")
    client.version.python
    ```
    """

    def __init__(self) -> None:
        self.sources = Sources()
        self.index = Index()
        self.settings = Settings()
        self.stats = Stats()
        self.search = Search()
        self.logs = Logs()
        self.db = Db()

    @property
    def version(self) -> VersionDetails:
        """The VethuQ version, Python version, platform and database schema in use."""
        return _VersionInfo.details()
